### PR TITLE
Adds pcntl extension to all PHP docker images

### PR DESCRIPTION
**Pull request by mmenozzi**
Hi guys,
I think that the **pcntl** extension should be included by default. It's required by `phpunit/php-invoker` package and [many others](https://packagist.org/packages/ext-pcntl/dependents).

- [x] My code passes relevant CI status checks. But I don't think that there is a CI check for the docker images builds.
- [x] No test applicable
- [x] My code includes documentation updates if relevant.
- [x] My code does not include an update to the `CHANGELOG` because I don't think that this change is so relevant but let me know if it should be there.
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by mmenozzi** [comment]
Hi @pirog, what do you think about this?

**Comment by uberhacker** [comment]
I think we probably need a few more extensions enabled than this, actually.  I did a comparison of a Pantheon hosted to the Lando version of the same site.  See below:

Pantheon:
```
'./configure' '--host=x86_64-redhat-linux-gnu' '--prefix=/opt/php7' '--with-libdir=lib64' '--disable-debug' '--with-pic' '--disable-rpath' '--without-pear' '--with-bz2' '--with-freetype-dir=/usr' '--with-png-dir=/usr' '--with-xpm-dir=/usr' '--enable-gd-native-ttf' '--with-t1lib=/usr' '--without-gdbm' '--with-gettext' '--with-gmp' '--with-iconv' '--with-jpeg-dir=/usr' '--with-openssl' '--with-pcre-regex=/usr' '--with-zlib' '--with-layout=GNU' '--enable-exif' '--enable-ftp' '--enable-sockets' '--with-kerberos' '--enable-shmop' '--enable-calendar' '--with-libxml-dir=/usr' '--enable-xml' '--with-mhash' '--enable-fpm' '--libdir=/usr/lib64/php' '--with-mysql=mysqlnd' '--disable-dba' '--with-unixODBC=/usr' '--without-pspell' '--with-curl=/usr' '--disable-posix' '--disable-sysvmsg' '--disable-sysvshm' '--disable-sysvsem' '--with-pdo-sqlite' '--with-pdo-mysql' '--with-mysqli=mysqlnd' '--with-pdo-pgsql' '--with-pgsql' '--with-imap' '--with-imap-ssl' '--with-gd' '--with-ldap' '--with-mcrypt' '--with-tidy=/opt/pantheon' '--enable-wddx' '--enable-bcmath' '--enable-dom' '--enable-fileinfo' '--enable-json' '--enable-mbstring' '--enable-pdo' '--enable-phar' '--enable-soap' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-zip' '--enable-opcache' '--with-imagick' '--enable-apcu' '--enable-apc-bc' '--enable-redis' '--enable-oauth' 'host_alias=x86_64-redhat-linux-gnu'
```
Lando:
```
'./configure' '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--disable-cgi' '--with-mhash' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-libdir=lib/x86_64-linux-gnu' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' 'build_alias=x86_64-linux-gnu'

Additional .ini files parsed
/usr/local/etc/php/conf.d/docker-php-ext-apcu.ini, /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini, /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini, /usr/local/etc/php/conf.d/docker-php-ext-calendar.ini, /usr/local/etc/php/conf.d/docker-php-ext-exif.ini, /usr/local/etc/php/conf.d/docker-php-ext-gd.ini, /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini, /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini, /usr/local/etc/php/conf.d/docker-php-ext-imap.ini, /usr/local/etc/php/conf.d/docker-php-ext-intl.ini, /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini, /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini, /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini, /usr/local/etc/php/conf.d/docker-php-ext-oauth.ini, /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini, /usr/local/etc/php/conf.d/docker-php-ext-redis.ini, /usr/local/etc/php/conf.d/docker-php-ext-soap.ini, /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini, /usr/local/etc/php/conf.d/docker-php-ext-zip.ini, /usr/local/etc/php/conf.d/xxx-lando-default.ini, /usr/local/etc/php/conf.d/zzz-lando-my-custom-ini-file-called-php.ini
```
As you can see, there are several extensions missing on the Lando side.  Most notably:
dom
fileinfo
freetype
gmp
iconv
imagick
jpeg
json
kerberos
mhash
pdo-sqlite
pcre
phar
shmop
sockets
tidy
unixODBC
wddx
xml (xmlreader/xmlwriter)
xsl

There are also several options purposely disabled.  I definitely think more work is needed to get the best Pantheon experience in Lando.

**Comment by pirog** [comment]
@uberhacker or anyone else who stumbles on this its worth pointing out that 

1. The difference list in https://github.com/lando/lando/pull/910#issuecomment-389896941 is not accurate
2. Lando and Pantheon use different methods to load in php extensions. Looks like Pantheon compiles them directly when they spin up php, Lando uses the mechanisms that Docker provides for its php images. The end result should be more or less the same
3. If you want to get the actual list of installed php extensions you'll want to run `lando php -me` or look at the `phpinfo();`

Here is an example of what `lando php -me` looks like on a Pantheon D7 site using `php 5.6`

```bash
lando.dev php -me                                                                                             ✓  11221  15:56:22
[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
OAuth
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

**Comment by uberhacker** [comment]
Based on what phpinfo() reported, I didn't see the extra extensions and since they didn't appear in the configure line or in the loaded extensions, I couldn't see if they were actually loaded.  Here is a vimdiff comparison of the php 7.0 loaded modules (Lando - left vs Pantheon - right):
```
    3 apcu                                                                                                             │    3 apcu                                                                                                            
      -----------------------------------------------------------------------------------------------------------------│    4 apm                                                                                                             
      5 bcmath                                                                                                           │    6 bcmath                                                                                                          
    6 bz2                                                                                                              │    7 bz2                                                                                                             
    7 calendar                                                                                                         │    8 calendar                                                                                                        
    8 Core                                                                                                             │    9 Core                                                                                                            
    9 ctype                                                                                                            │   10 ctype                                                                                                           
+  10 +--  3 lines: curl-----------------------------------------------------------------------------------------------│+  11 +--  3 lines: curl----------------------------------------------------------------------------------------------
   13 exif                                                                                                             │   14 exif                                                                                                            
   14 fileinfo                                                                                                         │   15 fileinfo                                                                                                        
   15 filter                                                                                                           │   16 filter                                                                                                          
   16 ftp                                                                                                              │   17 ftp                                                                                                             
   17 gd                                                                                                               │   18 gd                                                                                                              
   18 gettext                                                                                                          │   19 gettext                                                                                                         
      -----------------------------------------------------------------------------------------------------------------│   20 gmp                                                                                                             
   19 hash                                                                                                             │   21 hash                                                                                                            
   20 iconv                                                                                                            │   22 iconv                                                                                                           
   21 imagick                                                                                                          │   23 imagick                                                                                                         
   22 imap                                                                                                             │   24 imap                                                                                                            
   23 intl                                                                                                             │      ----------------------------------------------------------------------------------------------------------------
   24 json                                                                                                             │   25 json                                                                                                            
   25 ldap                                                                                                             │   26 ldap                                                                                                            
   26 libxml                                                                                                           │   27 libxml                                                                                                          
   27 mbstring                                                                                                         │   28 mbstring                                                                                                        
   28 mcrypt                                                                                                           │   29 mcrypt                                                                                                          
   29 mysqli                                                                                                           │   30 mysqli                                                                                                          
   30 mysqlnd                                                                                                          │   31 mysqlnd                                                                                                         
   31 OAuth                                                                                                            │   32 OAuth                                                                                                           
      -----------------------------------------------------------------------------------------------------------------│   33 odbc                                                                                                            
   32 openssl                                                                                                          │   34 openssl                                                                                                         
   33 pcre                                                                                                             │   35 pcre                                                                                                            
   34 PDO                                                                                                              │   36 PDO                                                                                                             
   35 pdo_mysql                                                                                                        │   37 pdo_mysql                                                                                                       
   36 pdo_pgsql                                                                                                        │   38 pdo_pgsql                                                                                                       
   37 pdo_sqlite                                                                                                       │   39 pdo_sqlite                                                                                                      
      -----------------------------------------------------------------------------------------------------------------│   40 pgsql                                                                                                           
   38 Phar                                                                                                             │   41 Phar                                                                                                            
   39 posix                                                                                                            │      ----------------------------------------------------------------------------------------------------------------
   40 readline                                                                                                         │      ----------------------------------------------------------------------------------------------------------------
   41 redis                                                                                                            │   42 redis                                                                                                           
   42 Reflection                                                                                                       │   43 Reflection                                                                                                      
   43 session                                                                                                          │   44 session                                                                                                         
      -----------------------------------------------------------------------------------------------------------------│   45 shmop                                                                                                           
   44 SimpleXML                                                                                                        │   46 SimpleXML                                                                                                       
   45 soap                                                                                                             │   47 soap                                                                                                            
      -----------------------------------------------------------------------------------------------------------------│   48 sockets                                                                                                         
   46 SPL                                                                                                              │   49 SPL                                                                                                             
   47 sqlite3                                                                                                          │   50 sqlite3                                                                                                         
   48 standard                                                                                                         │   51 standard                                                                                                        
      -----------------------------------------------------------------------------------------------------------------│   52 tidy                                                                                                            
   49 tokenizer                                                                                                        │   53 tokenizer                                                                                                       
   50 xdebug                                                                                                           │   54 wddx                                                                                                            
   51 xml                                                                                                              │   55 xml                                                                                                             
   52 xmlreader                                                                                                        │   56 xmlreader                                                                                                       
   53 xmlwriter                                                                                                        │   57 xmlwriter                                                                                                       
      -----------------------------------------------------------------------------------------------------------------│   58 xsl                                                                                                             
   54 Zend                                                                                                             │   59 Zend                                                                                                            
   55 zip                                                                                                              │   60 zip                                                                                                             
   56 zlib                                                                                                             │   61 zlib                                                                                                            
```
As you can see, more work is still needed to match the environments.

**Pull request merged**
