### PR TITLE
Fix .env file not loading when executing lando from non-app-root dire…

### PR DESCRIPTION
**Pull request by tylerssn**
This PR resolves `.env` files failing to load when lando is executed outside of the app directory (or within a subdirectory of the app) as described in #1045.

- [ ] My code includes an update to the [CHANGELOG](https://github.com/kalabox/lando/tree/master/docs/changelog)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [x] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [ ] [**n/a**] My code includes documentation updates if applicable.
- [x] My code passes relevant CI status checks
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can improve our process.

### CODE REVIEW

**Comment by tylerssn** [comment]
Pinging @dustinleblanc

**Comment by tylerssn** [comment]
I see that Travis CI is failing on the tests that I added. I will look into why that is.

**Comment by tylerssn** [comment]
@neclimdul - The tests were good all along on my machine, but the processing power was drastically slower on GitHub so the tests were timing out.

The tests are solid - but currently, require the Lando environment to spin-up for the test to complete.

**Comment by tylerssn** [comment]
@neclimdul - are you able to review/approve this PR?

**Comment by neclimdul** [comment]
No, I cannot approve anything.

**Comment by tanc** [comment]
I don't have write access but maybe @dustinleblanc or @pirog can double check and merge?

**Comment by dustinleblanc** [comment]
Hey folks! Sorry for being MIA, client work has been nuts lately and its been taking up a huge chunk of my time

**Comment by dustinleblanc** [comment]
Since you've been waiting so long on this one I'll see if I can quickly correct the test issue

**Comment by dustinleblanc** [comment]
Actually, the piece under test isn't even in a unit testable file, so really, we just need to port the test to our func testing suite

**Comment by dustinleblanc** [comment]
Discussing this with the maintainers about how to proceed with the test overlap question...

**Comment by tylerssn** [comment]
Yeah, my testing experience is light and evolving. I'll exercise my Google-Fu next time. Let me know if I can help further here.

In regard to mocking, I was hoping to implement that as opposed to spinning up an actual Lando environment but couldn't quite nail it down. My hunch was that not using a mock would have the biggest impact on whether or not this PR was acceptable.

**Comment by tylerssn** [comment]
@dustinleblanc I have refactored the test so that it implements Lando's functional test framework.

The `example/envfile/readme.md` has been updated, the test has been built by executing `yarn test:functional` and the test are passing.

One thing worth noting is that the functional test framework takes the keyword `lando` and converts it to `node ../../bin/lando.js` rather than an absolute path. This is problematic with the tests needed for the env file because the working directory has to differ from test to test. So, though my tests work the way they are setup now, it makes the `readme.md` a little more congested than it needs to be.

Also, I get that the path to the Lando.js file cannot be absolute so long as the functional tests are committed to the repository. The solution I'd like to propose is that functional tests not be included in the repository since they are regenerated each time `yarn test:functional` is executed. I'll open a ticket for this.

**Comment by tylerssn** [comment]
@dustinleblanc - just following up here. Is there anything needed from me in regard to the changes that you requested?

**Comment by pirog** [comment]
@tylerssn this ended up getting fixed as part 
https://github.com/lando/lando/pull/974#issuecomment-453836939

**Pull request closed without merging**
