### PR TITLE
Fixes #922

### LINKED ISSUE #922: Pantheon init fails with error: Cannot set property ‘id’
It looks like the platform sites API changed, so our API client needs to follow. PR to come

### PR DESCRIPTION
**Pull request by dustinleblanc**
Quick fix to a bug reported by users in Slack. Pantheon's API seems to have changed.

### CODE REVIEW

**Comment by skye-va** [comment]
When will beta.41 be available? I'm stuck not being able to init new Pantheon sites at the moment...

**Comment by pirog** [comment]
@skye-va https://github.com/lando/lando/releases/tag/v3.0.0-beta.41

**Comment by skye-va** [comment]
haha I walk away for 15 minutes and there it is!

**Comment by windycitymoon** [comment]
@pirog 
Thanks for the fast fix on this. 
Curious, did you try testing that fix out? Beyond the $ lando init pantheon?
It validates now, but then I'm unable to fetch a listing of projects from pantheon, in the next step. 
It's just shows undefined.  I'm trying to move from Kalabox to Lando at the moment. 
@skye-va Any luck here?

**Comment by serhatozkara** [comment]
I have the undefined site also...

**Comment by dustinleblanc** [comment]
@windycitymoon we have tested it and multiple folks are getting the right behavior. I am unsure what is causing the problem for you and @skye-va but I would assume Kalabox is involved

**Comment by windycitymoon** [comment]
@dustinleblanc would you recommend completely removing Kalabox? I'm fine with that if it means getting my setup current

**Comment by serhatozkara** [comment]
`lando init pantheon -- -v
info: Bootstraping...
info: Configuring app plugin
info: Configuring engine plugin
info: Configuring proxy plugin
info: Initializing proxy plugin
info: Configuring services plugin
info: Initializing app plugin
info: Initializing engine plugin
info: Initializing events
info: Initializing init framework
info: Initializing recipes plugin
info: Initializing services
info: Initializing tooling plugin
info: Initializing core plugin
info: Configuring networking plugin
info: Bootstrap completed.
info: Initializing cli
? Choose a Pantheon account serhatozkara@gmail.com
info: Making postJson request to api,authorize,machine-token
info: Making postJson request to api,authorize,machine-token
info: Making get request to api,users,1cefb2de-a483-42d6-8261-
info: Making get request to api,users,1cefb2de-a483-42d6-8261-
info: Got session: {"session":"1cefb2de-a483-42d6-8261-:-4cb7-11e8-99b6-42010a800160:6OPORJE2kMMSjuW4YIfnc","expires_at":1527540562,"user_id":"1cefb2de-a483-42d6-8261-"} for user serhatozkara@gmail.com
info: Making get request to api,users,1cefb2de-a483-42d6-8261-,sites
info: Got session: {"session":"1cefb2de-a483-42d6-8261-e0c6af2233bb:f62d9396-4cb7-11e8-8abd-:","expires_at":1527540562,"user_id":"1cefb2de-a483-42d6-8261-"} for user serhatozkara@gmail.com
info: Making get request to api,users,1cefb2de-a483-42d6-8261-,memberships,organizations
**? Which site? undefined**
landoinitlandoapp_util_1 is up-to-date
Scanning /user/.ssh for keys...
Scanning /lando/keys for keys...
Checking whether /user/.ssh/config is a private key...
Checking whether /user/.ssh/id_rsa is a private key...
Checking whether /user/.ssh/id_rsa is formatted correctly...
Checking whether /lando/keys/pantheon.lando.id_rsa is a private key...
Checking whether /lando/keys/pantheon.lando.id_rsa is formatted correctly...
Ensuring permissions for /user/.ssh/id_rsa...
Ensuring permissions for /lando/keys/pantheon.lando.id_rsa...
Using the following keys: /user/.ssh/id_rsa /lando/keys/pantheon.lando.id_rsa
info: Making postJson request to api,users,1cefb2de-a483-,keys
landoinitlandoapp_util_1 is up-to-date
Cloning into '.'...
ssh: Could not resolve hostname codeserver.dev.0.drush.in: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: 
`

**Comment by pirog** [comment]
@windycitymoon i did indeed test it (we run lots of tests before pushing a new release) but i can def confirm there is a subset of users that are experiencing this

**Comment by pirog** [comment]
@dustinleblanc https://github.com/lando/lando/commit/f14301cf493e627129e0ca77ba6342ff7324a968

Can replicate and fix above #922. There is another hotfix needed for #927 but once that is in ill roll a new release

**Pull request merged**
