### PR TITLE
#711: Fix lando pull for wordpress nested web root.

### PR DESCRIPTION
**Pull request by serundeputy**
Reroll of https://github.com/lando/lando/pull/710/files against latest master.
@dustinleblanc give it a whirl.

### CODE REVIEW

**Comment by serundeputy** [comment]
@dustinleblanc @pirog i am able to reproduce the not found errors:

```bash
geoff@yep 711-lpr (master) exit code: [0] $ lando.dev pull --code none --database dev --files none
/bin/sh: 1: ./pull.sh: not found
```

When I ssh into the `appserver` this is what the permissions on the `*.sh` scripts inside `/helpers` look like:

```bash
geoff@yep 711-lpr (master) exit code: [0] $ lando.dev ssh
www-data@ed0be986c02e:/app$ cd /helpers/
www-data@ed0be986c02e:/helpers$ ls
mysql-export.sh  mysql-import.sh  pantheon.sh  pull.sh	push.sh  switch.sh
www-data@ed0be986c02e:/helpers$ ls -alh
ls: cannot access 'pantheon.sh': No such file or directory
ls: cannot access 'pull.sh': No such file or directory
ls: cannot access 'mysql-export.sh': No such file or directory
ls: cannot access 'switch.sh': No such file or directory
ls: cannot access 'push.sh': No such file or directory
ls: cannot access 'mysql-import.sh': No such file or directory
total 8.0K
drwxr-xr-x 2 root root 4.0K Mar  4 16:57 .
drwxr-xr-x 1 root root 4.0K Mar  4 16:57 ..
-????????? ? ?    ?       ?            ? mysql-export.sh
-????????? ? ?    ?       ?            ? mysql-import.sh
-????????? ? ?    ?       ?            ? pantheon.sh
-????????? ? ?    ?       ?            ? pull.sh
-????????? ? ?    ?       ?            ? push.sh
-????????? ? ?    ?       ?            ? switch.sh
```

I'm guessing when we mount these helpers in the container we are not setting the permissions correctly and then we can not use them.

**Comment by serundeputy** [comment]
I checked out `beta.35` and here is what the permissions look like on that version of lando:

```bash
www-data@5048f26b1590:/app$ ls -alh /helpers/
total 40K
drwxr-xr-x 2 root     root     4.0K Mar  4 17:25 .
drwxr-xr-x 1 root     root     4.0K Mar  4 17:25 ..
-rwxr-xr-x 1 www-data www-data 2.4K Mar  4 17:25 mysql-export.sh
-rwxr-xr-x 1 www-data www-data 3.8K Mar  4 17:25 mysql-import.sh
-rwxr-xr-x 1 www-data www-data 1.6K Mar  4 17:25 pantheon.sh
-rwxr-xr-x 1 www-data www-data 5.9K Mar  4 17:25 pull.sh
-rwxr-xr-x 1 www-data www-data 4.5K Mar  4 17:25 push.sh
-rwxr-xr-x 1 www-data www-data 1.7K Mar  4 17:25 switch.sh
```

**Comment by pirog** [comment]
@dustinleblanc is that a pantheon site you can share with me so i can try to replicate/fix?

**Comment by serundeputy** [comment]
@pirog these two sites can be used to replicate:

* https://dashboard.pantheon.io/sites/884ffa52-3002-43f8-88d9-de6cafd80288#dev/code
* https://dashboard.pantheon.io/sites/899e912a-f7bd-4f8f-a714-4f945117b156#dev/code

**Comment by serundeputy** [comment]
I did some more investigation on mysql commands this weekend and it seems like the permissions on the `/helpers` and other `.sh` scripts are fine when you first start lando, but after issuing one of the sql commands `lando pull` for instance, it fails and then the permissions go wonky.

**Pull request merged**
