### PR TITLE
Add recipe for the PHP Magento 2 Framework

### PR DESCRIPTION
**Pull request by tylerssn**
This PR provides a starting point for collaboration on a Magento 2 recipe.

One of the biggest barriers to entry for new Magento developers is getting a dev environment up and running in M2 and I believe adding support to Lando will fuel it's growth significantly.

On another note, I am sure this should have been opened as an issue first for the community to discuss, so, I will follow up with an issue linking to this PR to see if it gains traction.

This PR provides:

- Tutorial documentation for getting up and running with Magento 2
- A Magento 2 recipe (currently locked to NGINX)
  - Redis & Database service versions are default to Magento 2.3 suggested versions
- Additional tooling:
  - Magento Cli 
  - Magerun Cli (Additional open source Magento tooling)
  - `magento:env:apply` tooling for configuring Magento to use Lando services
  - `magento:fresh` tooling for devs who want a "quick install" and "quick reset" option for new projects

Items to consider:
- Updating the recipes `builder.js` to accept `false` on cache & session service config in order to remove the services from the recipe.
- Promping for Magento composer authentication keys on `lando init`
  - This is unlikely to be needed since composer will automatically request the credentials if Lando cannot find them.
- The functional for `create-project` has some `composer config` magic in it so that the test can build the Magento project without being prompted for Magento keys. I'm pointing this out in case it concerns the Lando team that the Magento Example slightly differs from the "Getting Started" tutorial
- Magento recommends using ElasticSearch 5.2. For now, this is not included in the recipe because it tends to load slowly and, in general, just piss Lando off. If this PR is of interest to the Lando team then we may have to consider how or if we deal with ElasticSearch at all.

State of the PR
-
- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/changelog)
- [x] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [x] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by tylerssn** [comment]
I'd like to see this remain open just a little longer. I will not "unstale" if it "staled" again.

**Comment by pirog** [comment]
unstale

**Comment by tylerssn** [comment]
Unstale

**Comment by pirog** [comment]
@tylerssn id like to finally get this in! We've got a new "experimental" mode we are going to roll out in the next release and this seems like a good candidate. 

That way we can start to roll it out to more adventurous users and have them help us get it "production ready" for the rest of Lando. 

Are you still interested and able to help?

**Comment by tylerssn** [comment]
@pirog, I connected with @serundeputy on this in Slack. I will help however I can.

**Comment by tylerssn** [comment]
If we want to take a step back and drastically clean-up/simplify the Magento install mechanism, [mage2me](https://github.com/improper/mage2me) should be a good stand-in replacement. It's simply `laravel new` for Magento.


- GitHub token authentication & validation prior to download
- Magento public/private key authentication & validation prior to download
- Magento Edition and Version Validation with clear error messages
  - You can specify Commerce (enterprise) or Open Source edition
  - When the version is specified (2.2, 2.3.x, 2.4-develop) mage2me will validate that the version exists for the Magento edition that you requested prior to launching `composer create-project`.
- Nice, clear error messages each step of the way
- Nicely compiled executable allowing it to be standalone and installed globally
- Should be fully compatible with Windows, OSX and Linux
- Improved directory validation

**Pull request closed without merging**
