### PR TITLE
Added support for having a custom name for .env file

### PR DESCRIPTION
**Pull request by colynb**
Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**

- [x] My code passes relevant CI status checks
- [ ] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [x] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by dustinleblanc** [comment]
Thanks for contributing @colynb !

Can you open up an issue on the issue queue so that we can discuss this change? While it's cool to think up an addition to the project, we should precede that with a discussion about whether the maintainer team wants to add the feature or not. Since we haven't had that discussion yet, this PR will sit for at least a bit while we decide if it should even happen.

Thanks!

**Comment by colynb** [comment]
This makes total sense. Today will be very busy for me but I will try to
have that tonight. Thanks!

**Comment by colynb** [comment]
@dustinleblanc I submitted the issue for this at https://github.com/lando/lando/issues/994

**Comment by dustinleblanc** [comment]
Thanks @colynb I support this idea, especially given your issue outline is something I experience with laravel, and Laravel world domination is on my hit list for Lando. Just waiting for input from the rest of the maintainer team before moving forward on review

**Comment by ro0NL** [comment]
any chance this can be pushed into next 3.0.0? It's really annoying when working with Symfony also.

**Comment by pirog** [comment]
We are changing the way we handle env files in RC2. You will now be able to do something like

```yaml
# The name of my application
name: trivial-env
# A list of envvironment files to load relateive to my app root directory
env_file:
  - ./defaults.env
# A list of docker compose files to load relative to my app root directory
compose:
  - compose.yml
```

Under the hood this is now using `docker-compose`'s `env_file` instead of our own env loading and injection scheme which has the added benefits of being less code and also providing defaults that can then get overridden using `environment` in a service override

See: https://github.com/lando/lando/commit/c6c2646c4fba232f8b1899de3ef5f684756942e0

**Pull request closed without merging**
