### PR TITLE
Enabled the chrome-headless service.

### PR DESCRIPTION
**Pull request by mikemilano**
This PR includes headless chrome service and tests.

### CODE REVIEW

**Comment by mikemilano** [comment]
@pirog This PR is ready to merge if tests pass. I've updated kitchensink as well.

**Comment by pirog** [comment]
@mikemilano the tests did very much not pass, whats up with that?

**Comment by pirog** [comment]
@mikemilano ahh interesting, looks like CCI is reporting

```
Cloning into '.'...
Permission denied (publickey).

fatal: Could not read from remote repository.
```

I wonder if there was a temporary hiccup on the p.sh side. Let me restart the tests.

**Comment by pirog** [comment]
@mikemilano restarting tests seems to have worked. ghosts in the machine i guess!

**Pull request merged**
