### PR TITLE
Symfony recipe and documentation

### PR DESCRIPTION
**Pull request by mikemilano**
Thank you so much for contributing code to Lando! If this is your **first time** contributing to Lando we recommend you check out

* [Contributing to Lando](https://docs.devwithlando.io/contrib/contributing.html)
* [Lando Developer Guide](https://docs.devwithlando.io/dev/started.html)

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/changelog)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [x] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by pirog** [comment]
unstale

**Comment by mikemilano** [comment]
Notes to run functional tests that are failing:
```
yarn generate-tests
yarn mocha --timeout 9000 test/symfony-example.func.js
```

Output:

> symfony-example
>     ✓ should poweroff (402ms)
>     1) initialize an empty symfony recipe
>     2) should compose create project a new symfony app
>     3) should start up successfully
>     4) should return the symfony default page
>     5) should use 7 3 as the default php version
>     6) should be running apache 2 4 by default
>     7) should be running mysql 5 7 by default
>     ✓ should not enable xdebug by default (164ms)
>     8) should have redis running
>     ✓ should use the default database connection info (192ms)
>     ✓ should have console available (171ms)
>     ✓ should be destroyed with success (6941ms)
> 
> 
>   5 passing (5m)
>   8 failing
> 
>   1) symfony-example
>        initialize an empty symfony recipe:
>      Error: Command failed: rm -rf symfony && mkdir -p symfony && cd symfony && lando init --source cwd --recipe symfony --webroot /app/public --name lando-symfony --option cache=redis
> lando init
> 
> Initializes code for use with lando
> 
> Options:
>   --clear           Clears the lando tasks cache  [boolean]
>   --help            Shows lando or delegated command help if applicable  [boolean]
>   --verbose, -v     Runs with extra verbosity  [count]
>   --full            Dump a lower level lando file  [boolean] [default: false]
>   --github-auth     A GitHub personal access token  [string]
>   --github-repo     GitHub git url  [string]
>   --name            The name of the app  [string]
>   --option, -o      Merge additional KEY=VALUE pairs into your recipes config  [array]
>   --pantheon-auth   A Pantheon machine token  [string]
>   --pantheon-site   A Pantheon site machine name  [string]
>   --recipe, -r      The recipe with which to initialize the app  [string] [choices: "pantheon", "backdrop", "drupal6", "drupal7", "drupal8", "joomla", "lamp", "laravel", "lemp", "mean", "wordpress"]
>   --remote-options  Some options to pass into either the git clone or archive extract command  [string] [default: ""]
>   --remote-url      The URL of your git repo or archive, only works when you set source to remote  [string]
>   --source, --src   The location of your apps code  [string] [choices: "cwd", "github", "pantheon", "remote"]
>   --webroot         Specify the webroot relative to app root  [string]
>   --yes, -y         Auto answer yes to prompts  [boolean] [default: false]
> 
> Invalid values:
>   Argument: recipe, Given: "symfony", Choices: "pantheon", "backdrop", "drupal6", "drupal7", "drupal8", "joomla", "lamp", "laravel", "lemp", "mean", "wordpress"
> 
>       at ChildProcess.exithandler (child_process.js:289:12)
>       at maybeClose (internal/child_process.js:962:16)
>       at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 
>   2) symfony-example
>        should compose create project a new symfony app:
>      Error: Command failed: cd symfony && lando composer create-project symfony/website-skeleton tmp && cp -r tmp/. . && rm -rf tmp
> cp: tmp/.: No such file or directory
> 
>       at ChildProcess.exithandler (child_process.js:289:12)
>       at maybeClose (internal/child_process.js:962:16)
>       at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 
>   3) symfony-example
>        should start up successfully:
>      Error: Timeout of 9000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
>   
> 
>   4) symfony-example
>        should return the symfony default page:
>      Error: Timeout of 9000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
>   
> 
>   5) symfony-example
>        should use 7 3 as the default php version:
>      Error: Command failed: cd symfony && lando php -v | grep "PHP 7.3"
> Usage: lando <command> [args] [options]
> 
> Commands:
>   lando blog      Launch the blog
>   lando config    Displays the lando configuration
>   lando destroy   Destroys your app
>   lando docs      Launch the documentation site
>   lando events    Launch the events listing
>   lando info      Prints info about your app
>   lando init      Initializes code for use with lando
>   lando list      Lists all running lando apps and containers
>   lando logs      Displays logs for your app
>   lando node      Runs node commands
>   lando platform  Run Platform CLI commands
>   lando poweroff  Spins down all lando related containers
>   lando rebuild   Rebuilds your app from scratch, preserving data
>   lando restart   Restarts your app
>   lando share     Shares your local site publicly
>   lando site      Launch the marketing site
>   lando ssh       Drops into a shell on a service, runs commands
>   lando start     Starts your app
>   lando stop      Stops your app
>   lando version   Displays the lando version
>   lando vuepress  Runs vuepress commands
>   lando yarn      Runs yarn commands
> 
> Options:
>   --clear        Clears the lando tasks cache  [boolean]
>   --help         Shows lando or delegated command help if applicable  [boolean]
>   --verbose, -v  Runs with extra verbosity  [count]
> 
> Examples:
>   lando start            Run lando start
>   lando rebuild --help   Get help about using the lando rebuild command
>   lando destroy -y -vvv  Run lando destroy non-interactively and with maximum verbosity
>   lando --clear          Clear the lando tasks cache
> 
> Did you mean stop?
> 
>       at ChildProcess.exithandler (child_process.js:289:12)
>       at maybeClose (internal/child_process.js:962:16)
>       at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 
>   6) symfony-example
>        should be running apache 2 4 by default:
>      Error: Timeout of 9000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
>   
> 
>   7) symfony-example
>        should be running mysql 5 7 by default:
>      Error: Command failed: cd symfony && lando mysql -V | grep 5.7
> 
>       at ChildProcess.exithandler (child_process.js:289:12)
>       at maybeClose (internal/child_process.js:962:16)
>       at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 
>   8) symfony-example
>        should have redis running:
>      Error: Timeout of 9000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
>   
> 
> 
> 
> error Command failed with exit code 8.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by pirog** [comment]
@mikemilano as part of this PR it might be good to update our func test docs to include steps on how to run a single test file instaed of the whole suite

**Comment by pirog** [comment]
@mikemilano here is hte folder for new experimental stuff
https://github.com/lando/lando/tree/master/experimental/plugins/lando-experimental

And the docs around the flag
https://docs.lando.dev/config/experimental.html

**Comment by limitstudios** [comment]
Do this PR need any assistance happy to help get it across the line for Symfony 4/5?

**Comment by pirog** [comment]
If you want to try it out and give feedback that would be great!

**Pull request merged**
