### PR TITLE
Add support for .mjs file extension by sending correct MIME type

### PR DESCRIPTION
**Pull request by felixarntz**
This PR ensures `.mjs` files are handled properly on Nginx. This file extension is typically used for JavaScript modules (see https://developers.google.com/web/fundamentals/primers/modules), so such files should send the `application/javascript` MIME type header.

- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/changelog)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [ ] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by pirog** [comment]
@felixarntz seems reasonable but i am not super knowledgeable about this. Can you point me to any relevant documentation about possible implications of setting this?

@dustinleblanc you have any knowledge/thoughts about this?

**Comment by felixarntz** [comment]
> Can you point me to any relevant documentation about possible implications of setting this?

I'm not sure about any documentation, but setting this will ensure such files are served with the correct MIME type. Currently, the browser will display an error, because `.mjs` files are not served as `application/javascript`.

**Comment by dustinleblanc** [comment]
I'd normal refer to https://www.iana.org/assignments/media-types/media-types.xhtml for this type of question but I don't see mjs on there. From what I've been reading, the convention is to use .js outside of a Node context (in the browser). @felixarntz do you know what browser support for this is like?

**Comment by felixarntz** [comment]
@dustinleblanc JavaScript modules in the browser are a quite new technology, but it is fairly well supported already, see https://caniuse.com/#search=modules. As stated in the article https://developers.google.com/web/fundamentals/primers/modules, the usage of `.mjs` as file extension is a best practice (indeed taken over from the server-side Node world), but in order to allow browsers to support that format, the server needs to send the correct MIME type `application/javascript`. Especially as Lando is geared towards developers, I think this should be supported, even if it's currently not (yet) in the IANA list you linked to.

**Comment by dustinleblanc** [comment]
Yeah I use the IANA list as a reference only because Pantheon has always done so (and I used to work there, so this kind of thing I default to that way of doing things/knowledge).

It's probably fine to include it.

**Comment by felixarntz** [comment]
What's the state on this? Just following up since it warns about auto-closing :)

**Comment by pirog** [comment]
@felixarntz i think its something we intend to merge but we've just been distracted with other stuff lately :(

**Comment by felixarntz** [comment]
Bump :)

**Comment by felixarntz** [comment]
Bump.

**Comment by felixarntz** [comment]
Bump.

**Pull request merged**
