### PR TITLE
Update Terminus 1 9 0

### LINKED ISSUE #1259: Update Terminus to v1.9.0
**Tell us about your setup**

v3.0.0-rc.1

**Tell us about the command you were running**

lando start

**Tell us about the error you got**

```
[notice] A new Terminus version v1.9.0 is available.
You are currently using version v1.8.1.
You can update Terminus by running `composer update` or using the Terminus installer:
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update
```

### PR DESCRIPTION
**Pull request by philltran**
Fixes #1259

### CODE REVIEW

**Comment by philltran** [comment]
I corrected the version to 3.0.0-rc.2. Thanks.

**Comment by wenzowski** [comment]
@dustinleblanc is something still blocking merge on this?

**Comment by pirog** [comment]
@wenzowski looks like we need to update the PR with master and i wouldn't mind seeing some functional tests added to the pantheon suite for this either.

**Comment by philltran** [comment]
Hi

I updated to master. 

What type of functional test are you thinking of adding? Any specific commands you want tested?

**Comment by dustinleblanc** [comment]
@philltran I think in this case, it would just be that Terminus works so something like:

```
lando start

lando terminus self:info | grep "terminus_version"
```
Or something similar should work

**Pull request closed without merging**
