### PR TITLE
proxy docs: add info on connecting from other devices on local network

### PR DESCRIPTION
**Pull request by ptmkenny**
- [X] My code includes documentation updates if relevant.
- [X] I have pinged @pirog/@reynoldsalec/@serundeputy when I think my code is ready for prime time.

@pirog @serundeputy Here's an addition to the docs to address connecting to lando via devices on a local network; this was requested in the kalabox issue queue: https://github.com/kalabox/kalabox/issues/1807

I just set this up for myself today so I thought I would share my notes.

### CODE REVIEW

**Comment by pirog** [comment]
@ptmkenny this is great but it might be worth mentioning and linking to the `lando share` docs since that is also a pretty good way to do this. Thoughts?

**Comment by ptmkenny** [comment]
@pirog Darn, I overlooked the `lando share` command, that's awesome.  I added it to the top of the documentation and put it as the recommended method since it works over the Internet and not just a local network, and I put the local IP method second if people don't want the app exposed to the Internet.

**Comment by pirog** [comment]
@ptmkenny yeah `lando share` is one of those hidden gems :)

So i think this looks great. My only question is do you think it makes more sense to have this be part of the proxy documentation or its own separate tutorial?

**Comment by ptmkenny** [comment]
@pirog  It might be easier to find if this was its own section with a title like "Access from Other Devices".

**Comment by pirog** [comment]
@ptmkenny exactly. what i would do is spin up a new file called `access-other-devices.md` (or something similar) and drop it into the tutorial folder in the docs. Then i would update the `SUMMARY.md` to include this as a tutorial.

**Comment by ptmkenny** [comment]
@pirog Done!

**Comment by pirog** [comment]
@ptmkenny awesome! thanks so much! really appreciate all you've done to help the project!

**Pull request merged**
