### PR TITLE
#511 blackfire support

### PR DESCRIPTION
**Pull request by dustinleblanc**
@pirog this should be good for review

I didn't add any tests for this one, we could consider a test strategy for services in the near future.

- [x] My code passes relevant CI status checks
- [ ] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [x] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by dustinleblanc** [comment]
WINDOWZZZZZZ

**Comment by mmenozzi** [comment]
@dustinleblanc What's missing to have this merged?

**Comment by dustinleblanc** [comment]
@mmenozzi It needs feature and/or unit tests

**Comment by mmenozzi** [comment]
Would make sense to split this into two separate PRs? One for the blackfire agent service and another to have blackfire php extension installed on the php docker image. What do you think?

**Comment by dustinleblanc** [comment]
Installation in the containers requires building a publishing new docker images as well. There really isn't a reason to split them up. Arguably installing the extension in all PHP services has likelylhood to cause issues and therefore needs tests. I'd go ahead and give this feature a +1, @awolfey also said he was interested, we should be able to get it wrapped up someday, we're all just quite busy. If someone wants to write the tests though I'd be happy to review when I have a minute

**Comment by mmenozzi** [comment]
I could try to do this but it would be my first contribution to lando (at least for the js code) so don’t count on me. :)

**Comment by dustinleblanc** [comment]
@pirog the tests I asked @mmenozzi to write require the pushed modifications to the dockerfiles to be in place to pass, this is a bit of a chicken/egg issue. How do you want to handle that kind of weirdness?

**Comment by mmenozzi** [comment]
@dustinleblanc also the test which checks if the blackfire agent runs is failing but I think that is a race condition because even on my machine it fails the first time but then, when the container is fully started, it passes. How can we fix that?

**Comment by dustinleblanc** [comment]
That's a good question @mmenozzi and I think a bigger one for this test suite as it grows. How do we prime that cache so that the docker images are always present? We also need to get around to fixing our testing configuration with Circle. I am still skeptical that the tests are running correctly

**Comment by mmenozzi** [comment]
Ok @dustinleblanc I understand that test suite needs more work to be more reliable. Anyway I would track that work on a separate issue without blocking other feature development (like this). What do you think?

**Comment by dustinleblanc** [comment]
See #983, we can track those fixes there. I think this branch is good, I just want to get @pirog's feedback on the test state given where we are at the moment.

**Comment by javivf** [comment]
I'm trying to use this feature but I'm getting this error when I run `lando start:` 

`error: (HTTP code 500) server error - container ede42641442f9146a5f68bb35ba4f5cec45e9a8f9dd54653025b3660a9122b67 is not connected to the network lando_bridge_network`

any clue?

**Comment by pirog** [comment]
@dustinleblanc im going to close this for now (but keep the branch alive) since we need to

1. Port to stable release (eg RC2+) plugin system
2. Get "lando plugin" helpers working

**Pull request closed without merging**
