### PR TITLE
Fix lando pull bug on pantheon wordpress sites 

### LINKED ISSUE #711: Current master has all sql commands failing; db-import, db-export, pull, push; lando pull db fails for pantheon recipe
In our site the wordpress files are not inside the root directory (i.e. they exist in `/web`). When running `lando pull --database=dev --files=none --code=none` the command will fail at the end when replacing dev URLs with local URLs. 

*Error message*
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

*System*
v3.0.0-beta.36 on macOS Sierra

*.lando.yml*
```
name: super-awesome-site
recipe: pantheon
config:
  framework: wordpress
  site: super-awesome-site
  id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

*pantheon.yml*
```
api_version: 1
php_version: 5.6
web_docroot: true
```

### PR DESCRIPTION
**Pull request by msschwartz**
Fixes #711.

If wordpress files are not in the root directory `lando pull` will throw error. When the `wp search-replace` command fires the following error message appears:
> Error: This does not seem to be a WordPress install.
> Pass --path=`path/to/wordpress` or run `wp core download`.

---

- [x] My code passes relevant CI status checks
- [x] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [x] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/committer.html) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by msschwartz** [comment]
Not sure what technique should be used for pinging a project committer. But I think this is ready. Very minor bug fix. @dustinleblanc

**Comment by dustinleblanc** [comment]
@msschwartz Thanks for the PR! I've updated the branch to accommodate recent changes and I'll merge after CI passes. Welcome to the party!

**Comment by dustinleblanc** [comment]
Hey @msschwartz I actually went ahead and cloned this down locally to just run a manual functional test and I am having a bit of a problem:

```sh
lando.dev pull
? Pull code from? none
? Pull DB from? dev
? Pull files from? dev
/bin/sh: 1: /helpers/pull.sh: not found
```
Can you confirm if you get the same thing after the branch had master merged in? We may have introduced another issue but I want to be careful as a lot of people use this feature.

**Comment by msschwartz** [comment]
I'm seeing the same error after pulling your changes. I'll look into what's going on a publish a fix shortly.

**Comment by dustinleblanc** [comment]
@msschwartz Its possible something upstream got broken, so at the moment, I'll leave this open until we can figure that out

**Comment by serundeputy** [comment]
@msschwartz i'm closing this one in favor of reroll at https://github.com/lando/lando/pull/722 ; I've cherry-picked your work out into that one.

**Pull request closed without merging**
