### PR TITLE
Make sure GD is compiled with freetype

### PR DESCRIPTION
**Pull request by hussainweb**
Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**

- [x] My code passes relevant CI status checks
- [x] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [ ] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by hussainweb** [comment]
@dustinleblanc, could I bother you for a review? I think the coveralls issue has been resolved.

**Comment by hussainweb** [comment]
@dustinleblanc, thanks for replying.

I am not really sure why it was not enabled. I have rarely come across a setup where I had to explicitly enable it. For example, the [README](https://github.com/docker-library/docs/blob/master/php/README.md#php-core-extensions) for PHP Docker image gives an example of gd along with freetype configured.

As for impact, I don't think there is a negative impact. The freetype libraries are already present in the image. It's just the PHP bindings which need to be configured (and that is just a flag on an already existing extension). The difference it makes in PHP configuration is visible on `phpinfo()` page under GD section.

OTOH, there are functionalities that need this. In my case, it is required by the [image_effects](https://www.drupal.org/project/image_effects) module to render text to images.

Thanks again for looking at this and replying. I am happy to help in any other way I can.

**Comment by neclimdul** [comment]
@dustinleblanc just so you know, pretty sure this broke your 5.3 builds.
https://hub.docker.com/r/devwithlando/php/builds/buznxkm2nftiqk9nf9ka3c9/

**Comment by dustinleblanc** [comment]
Thanks for the heads up @neclimdul

**Comment by dustinleblanc** [comment]
Created #1141 as a follow up

**Pull request merged**
