### PR TITLE
Update 'From source' section in installation.md

### PR DESCRIPTION
**Pull request by uberhacker**
- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
- [ ] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [x] My code includes documentation updates if applicable.
- [x] My code passes relevant CI status checks
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Review by hotwebmatter — APPROVED** [review]
Animated gif of a bearded guy doing something cool with a computer in the 1980s

Nice work, computer guy

Image of ASCII art spelling out LGTM, an acronym for Looks Good To Me
/approved

**Comment by hotwebmatter** [comment]
Actually, maybe not approved.

It seems like the bespoke path for Lando dependencies might work with the new [Hyperdrive](https://github.com/lando/hyperdrive).

```
$ grep -rn /usr/share/lando
test/env.spec.js:59:      expect(dockerBinPath).to.equal('/usr/share/lando/bin');
test/env.spec.js:85:      filesystem({'/usr/share/lando/bin/docker-compose': 'CODEZ'});
test/env.spec.js:87:      expect(composeExecutable).to.equal('/usr/share/lando/bin/docker-compose');
lib/env.js:40:      return '/usr/share/lando/bin';
```

I don't have time to look into this at the moment, but it may be that the whole idea is for Lando to keep its own pinned version of `docker-compose` off the PATH, so that a newer version can be installed (by `brew`, `apt`, `yum`/`dnf` or whatever) and called interactively from the shell, without requiring Lando to use a newer version than it can handle.

If that's the case, then bravo -- I think it could be a huge win for Lando if it manages its own dependencies.

**Comment by uberhacker** [comment]
Thank you for the review @hotwebmatter!  Can you elaborate on the motivation for the `/usr/share/lando/bin/docker-compose` location when you get a chance @pirog?  My initial thought was why not use a location already in PATH?

**Comment by pirog** [comment]
Because we want to be able to ensure we use a version of docker-compose
that works with lando while not forcing the user to use our version of
docker-compose for all of their non-lando Docker things.

**Comment by uberhacker** [comment]
I guess that makes sense.  Should there be pre-flight checks to flag for the unsupported docker-compose version?

**Comment by hotwebmatter** [comment]
Makes sense to me @pirog.

Allowing Lando to manage its own dependencies will prevent a whole class of errors like this one:

```
 ■ Using an unsupported version of DOCKER COMPOSE
   You have version 1.29.1 but Lando wants something in the 1.23.0 - 1.29.0 range.
   If you have purposefully installed an unsupported version and know what you are doing
   you can probably ignore this warning. If not we recommend you use a supported version
   as this ensures we can provide the best support and stability.
   https://docs.docker.com/compose/install/#install-compose-on-linux-systems
```

With `/usr/share/lando/` I can install the very latest `docker-compose` on my `$PATH` and use that for all my non-Lando Docker things without worrying whether the version on my `$PATH` will break Lando.

:tada:

**Comment by uberhacker** [comment]
Alright, I restored the `/usr/share/lando/bin` path.  This should be ready for your review when you get a chance @pirog.

**Pull request merged**
