### PR TITLE
Updates wordpress.conf.tpl to support WordPress multisite

### PR DESCRIPTION
**Pull request by screid123**
## Adds missing rules from Pantheon nginx config to support WordPress multisite (site network). 

After some research and digging into the Pantheon recipe, I was able to get a WordPress site network running locally in Lando. I "hacked" my local by updating the `appserver_nginx` container to use modified TPLs (see below). This update basically adds the following to the `wordpress.conf.tpl` to support the rewrite rule for multisite (which I found by manually diffing the NGINX config I downloaded from our Pantheon instance via SFTP; lines ~379-392 in `nginx.conf`):

```
# Rewrite multisite '.../wp-.*' and '.../*.php'.
# Because even if the site is in a subdirectory at http://site.com/site-a/
# requests for the wp-admin, or other specific php files, need to go to the docroot.
if (!-e $request_filename) {
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) $1 last;
    rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ $1 last;
}
# Legacy site network files support.
location ~ ^/wp-content/blogs.dir/([_0-9a-zA-Z-]+)/files/(.*)$ {
    try_files /wp-content/blogs.dir/$1/files/$2 /wp-includes/ms-files.php?file=$2 ;
    access_log off; log_not_found off; expires max;
}
```

### References that led me down the rabbit hole:
- https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/#rewrite-rules-for-multisite
- https://docs.lando.dev/config/nginx.html#configuration
- https://docs.lando.dev/config/pantheon.html#configuration

### Background
Initially, I grabbed the `nginx.conf.tpl` and `wordpress.conf.tpl` from the [Pantheon recipe](https://github.com/lando/lando/tree/master/plugins/lando-pantheon/recipes/pantheon) and put them in the root `private` directory (which is protected in Pantheon environment). I added the same changes to `wordpress.conf.tpl` as this PR, and then updated `lando.yml` with the following:
```yaml
services:
  appserver_nginx:
    type: nginx
    config:
      server: 'private/config/nginx.conf.tpl'
      vhosts: 'private/config/wordpress.conf.tpl'
```
I performed a `lando rebuild` and it worked. Figured updating the source TPL might help other folks out (#157 and #1425 to name a couple). 😃 

---

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [x] My code includes the latest code from the `master` branch
- [x] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
- [ ] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by dustinleblanc** [comment]
This seems related to https://github.com/lando/lando/issues/2089

**Comment by dustinleblanc** [comment]
Thanks @screid123!

This looks like one component of what we'll need to resolve #1425. I just pulled your branch locally and I think I am going to combine it with some other stuff to get WP Site Network support for Pantheon dialed in.

**Comment by screid123** [comment]
Awesome! One note is that this doesn’t appear to help support subdomain networks. I believe these rules would just help subdirectory setups.

**Comment by dustinleblanc** [comment]
Thanks! There is more work to do around the Pantheon recipe actually supporting the proper framework flags for site networks too, so I suspect there will be opportunity to make some more edits to get that working. Right now I am waiting on getting access to a site network on Pantheon for testing, which will let me run through this with an actual site

**Comment by TMFEspresso** [comment]
@screid123 You're correct, those rules only do subfolder. It would be nice if there was a flag in the landofile that allowed you to swap between subfolder or subdomain. 

The subdomain nginx rules are here: https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/#rewrite-rules-for-multisite-using-subdomains

**Comment by dustinleblanc** [comment]
I did some work on this over the weekend with a Pantheon site that is setup to run on sub-domains and I was able to get it working. Lando's proxy already handles routing multiple domains to the appserver container, the same way Pantheon's edge handles this. After reviewing the nginx config on Pantheon as well, I am not sure we need to make any additional edits to the nginx config. I need to setup a dedicated site networks with Pantheon for testing

**Comment by screid123** [comment]
The version we were using would allow the front end of sites to load, but the admin side would error in an endless redirect loop when trying to visit a site other than the main/root site when using the subdirectory install. That’s what led me to modify the config lando was using. It was missing the rewrites for wp-admin and wp-includes in a subdirectory.

**Comment by dustinleblanc** [comment]
Hey @screid123! Sorry, I wasn't clear, I meant I don't think we need to make more changes _beyond what's in your pr_ :)

**Comment by dustinleblanc** [comment]
Pulled these commits into https://github.com/lando/lando/pull/2111, closing this one in favor of that one, you can see the extra magic I added on top on that PR

**Pull request closed without merging**
