### PR TITLE
Update lando-with-vscode.md

### PR DESCRIPTION
**Pull request by MatthieuScarset**
Remove now useless examples for old version of Lando.

Update example files content to provide latest working settings.

### CODE REVIEW

**Comment by reynoldsalec** [comment]
Hey @MatthieuScarset thanks for the contribution!

We've moved the docs to their own repo: https://github.com/lando/docs

Would you mind moving this PR over there? Thanks again for the help!

**Comment by reynoldsalec** [comment]
Closing this out in favor of https://github.com/lando/docs/pull/162

**Comment by MatthieuScarset** [comment]
Sorry I was not available earlier. Thank you for opening the PR on the other repo @reynoldsalec :ok_hand:

**Comment by reynoldsalec** [comment]
NP, hope I got your credit right :)

**Pull request closed without merging**
