### PR TITLE
Update Backdrop link to always pull latest

### PR DESCRIPTION
**Pull request by laryn**
See https://github.com/backdrop/backdrop-issues/issues/5156

### CODE REVIEW

**Review by klonos — APPROVED** [review]
LGTM 👍🏼

**Comment by reynoldsalec** [comment]
Hey @laryn thanks for the contribution!

We've moved the docs to their own repo: https://github.com/lando/docs

Would you mind moving this PR over there? Thanks again for the help!

**Comment by laryn** [comment]
Done: https://github.com/lando/docs/issues/159

**Comment by reynoldsalec** [comment]
You are a rockstar, thanks!

**Pull request closed without merging**
