### PR TITLE
Make load-keys.sh compatible with MacOS High Sierra by removing group permissions check on keys

### PR DESCRIPTION
**Pull request by bwood**
We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [x] My code includes the latest code from the `master` branch
- [x] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
  - It doesn't seem appropriate to update `docs/help/2020-changelog.md` at this point.  If this PR is accepted, here is a suggestion: **Make load-keys.sh compatible with MacOS High Sierra by removing group permissions check on keys.**
- [ N/A ] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ N/A ] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ N/A ] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

----------

This small change resolves the MacOS High Sierra issue described in https://github.com/lando/lando/issues/1657#issuecomment-514937215. It does this by removing the check on the key file's group.  Under High Sierra the group check fails:

In the container `id` returns:
```
www-data@7d72e89ae306:/app$ id
uid=149902NNNN(www-data) gid=54999NNNN(www-data) groups=54999NNNN(www-data)
```
but when listing a key file the gid _appears_ not to match as the result of something strange about High Sierra:
```
www-data@7d72e89ae306:/app$ ls -ln /user/.ssh/id_rsa
-rw------- 1 149902NNNN 549 3381 Jun 16 16:18 /user/.ssh/id_rsa
```

Shout out to @dsnopek who helped debug!

### CODE REVIEW

**Comment by bwood** [comment]
@pirog Here's our slack conversation from yesterday:

```
pirog 4:37 PM
@Brian Wood that file is managed and updated by Lando so youd need to run from source and edit the source version of that file to get the intended change. im unclear on whether the group needs to verified or not, i think we just defaulted to the max secure check

Brian Wood 4:38 PM
Thanks.
im unclear on whether the group needs to verified or not, i think we just defaulted to the max secure check
4:39
The above makes sense. If the hack fixes it for my should I open a PR, or is High Sierra just too old? :slightly_smiling_face:
New

pirog 4:40 PM
lol thats a good question. we support what docker desktop supports, which is…. checking
4:40
macOS must be version 10.13 or newer. That is, Catalina, Mojave, or High Sierra. We recommend upgrading to the latest version of macOS.
4:41
so i guess officially that is not too old :wink:
4:41
in which case id def open a PR
```

**Comment by pirog** [comment]
nice @bwood, ive merged this into a consolidated testing branch over here https://github.com/lando/lando/pull/2419 hopefully it doesnt break anything ;)

**Comment by pirog** [comment]
alright @bwood that change passed the tests so its in `master` and will be in the next release this friday

**Comment by bwood** [comment]
Excellent!  Thanks!

**Pull request closed without merging**
