### PR TITLE
Update security.md

### PR DESCRIPTION
**Pull request by MichaelMallett**
You need to make it extremely clear that you're destroying data when an app is rebuilt. 

Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [ ] My code includes an update to the [CHANGELOG](https://github.com/kalabox/lando/tree/master/docs/changelog)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [ ] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can improve our process.

### CODE REVIEW

**Comment by dustinleblanc** [comment]
@pirog does rebuild really delete your db? I am pretty sure it doesn't...

**Comment by serundeputy** [comment]
@dustinleblanc @pirog I routinely `rebuild` and it does not delete my DB(s).

**Comment by MichaelMallett** [comment]
Hmmmm...it deleted mine. Deleted the container completely. Hence this issue
as I really wasn't expecting it

**Comment by pirog** [comment]
@MichaelMallett as far as i know this is not true, give us steps to replicate it and we will look into it more. 

@serundeputy this could be a good place for a functional test maybe on the db-import example?

```bash
# Import DB
# Rebuild app
# Check if DB still has tables
```

**Comment by serundeputy** [comment]
@pirog i've added tests to the `db-import` example to ensure that after a `lando rebuild` the data tables are still present.

So, far they have been there sample size 4.

https://github.com/lando/lando/pull/1209

**Comment by dustinleblanc** [comment]
Closing per #1209

**Pull request closed without merging**
