### PR TITLE
Fix manifest build thing

### LINKED ISSUE #796: Error in compose file, retries should be a number.
Bug Report
==========

lando source build on Ubuntu 17.10

`.lando.yml`
```yml
name: laraveltest
recipe: laravel
config:
  webroot: ./public/
  via: nginx
  php: '7.2'
```

Error:
```bash
lando.dev start
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... 
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
error: ErrorError: Error
    at /home/neclimdul/Programs/lando/lib/promise.js:55:17
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at rec (/home/neclimdul/Programs/lando/lib/promise.js:41:13)
    at /home/neclimdul/Programs/lando/lib/promise.js:49:20
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
From previous event:
    at /home/neclimdul/Programs/lando/lib/promise.js:48:12
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Failure to start because of some internal docker-compose processing error?

### PR DESCRIPTION
**Pull request by neclimdul**
Fix #796 

- [x] My code passes relevant CI status checks
- [ ] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [ ] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [ ] My code includes documentation updates if relevant.
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by neclimdul** [comment]
Ok, ran clean.

Was just getting this off my local machine and posted. Assumed without that and the last checkbox checked it wasn't going to disturb anything.

**Comment by neclimdul** [comment]
I'm happy to write a test but there doesn't seem to be any around manifests from what I can tell.

Mostly it causes this change
Before:
```
    healthcheck:
      test: mysql -uroot --silent --execute "SHOW DATABASES;"
      interval: 2s
      timeout: 10s
      retries: '25'
```

after:
```
    healthcheck:
      test: mysql -uroot --silent --execute "SHOW DATABASES;"
      interval: 2s
      timeout: 10s
      retries: 25
```

I assume the JSON->YAML conversion library is seeing the explicit string and keeping the type in YAML. Changing it to an integer/number in the JSON causes the same thing to happen in YAML and fixes the problem.

**Comment by dustinleblanc** [comment]
@neclimdul awesome, thanks! I think this is probably a solid first bugfix for the latest release, we'll let you know if it needs anything else. If you dig it, you can totally add tests too!

**Comment by dustinleblanc** [comment]
Thanks @neclimdul! Welcome to the contributor club 🎉

**Comment by pirog** [comment]
@neclimdul @dustinleblanc lets make sure we get these fixes into the changelog before we merge them in so we can drop them in the release notes!

i'll add this one in now

**Comment by dustinleblanc** [comment]
I did 😋 see 9a7f6b023e35c32c05e07ab076084e448d64e7bd

Looks like you twerked the formatting though 👍

**Comment by pirog** [comment]
I meant enforcing that the contributor has put in the entry themselves  so
we don’t have to manage it on our end

**Comment by dustinleblanc** [comment]
Ah got it

**Pull request merged**
