### PR TITLE
Fix travis macosx builds

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by pirog** [comment]
@serundeputy are the `travis_wait`s still required?

**Comment by serundeputy** [comment]
@pirog it's hard to say because at various times in the testing the timeouts were at different steps.

I think having them doesn't make it wait the whole time; just allows it to wait that long if necessary.

**Comment by pirog** [comment]
@serundeputy im guessing we should probably remove them and see if it still works then

**Comment by serundeputy** [comment]
@pirog build passed without the `travis_wait`s; thanks for clobbering the lingering `30`.

I think we are good to merge here.

**Pull request merged**
