### PR TITLE
Issue #2504: Skip permissions hardening by default on Pantheon apps

### PR DESCRIPTION
**Pull request by dustinleblanc**
I had some weird issues with running Drush on Drupal 8 with the default Pantheon settings.php files, but I managed to get it working and can confirm this works:
image

### CODE REVIEW

**Comment by pirog** [comment]
@dustinleblanc this looks good but do we want to add a test to our Drupal 8 pantheon example? Seems like that would be easy.

**Comment by pirog** [comment]
@dustinleblanc also should update the changelog i think!

**Comment by pirog** [comment]
@dustinleblanc might be worth doing a `yarn generate:tests` locally to work through the escaping problem showing up in the tests

**Comment by dustinleblanc** [comment]
@pirog definitely, I'll jump back on it after I finish the other auth stuff I am on

**Pull request merged**
