### PR TITLE
PR: Expand the supported range of SOLR service versions #513

### PR DESCRIPTION
**Pull request by jbertoen**
@pirog/@reynoldsalec/@serundeputy

### CODE REVIEW

**Comment by pirog** [comment]
@jbertoen nice! thanks! this is great. always happy to get more versions of things dialed. 

Looks like there are some small code standard things to clean up 

```
Running "jscs:cli" (jscs) task
Expected indentation of 4 characters at plugins/lando-services/solr/solr.js :
   192 |   */
   193 |  var volumes = function(name) {
   194 |      var vols = {};
------------^
   195 |      vols['data_' + name] = {};
   196 |      return vols;
Expected indentation of 4 characters at plugins/lando-services/solr/solr.js :
   193 |  var volumes = function(name) {
   194 |      var vols = {};
   195 |      vols['data_' + name] = {};
------------^
   196 |      return vols;
   197 |  };
Expected indentation of 4 characters at plugins/lando-services/solr/solr.js :
   194 |      var vols = {};
   195 |      vols['data_' + name] = {};
   196 |      return vols;
------------^
   197 |  };
   198 |
>> 3 code style errors found!
```

I'd obey the standards, push up a fix and then ping me again and ill test the stuff out so we can get this all merged!

**Comment by jbertoen** [comment]
Sorry about that, my bad. @pirog go ahead with testing!

**Comment by pirog** [comment]
@jbertoen no worries! thanks so much for your contribution. looking forward to testing this out.

**Comment by pirog** [comment]
@jbertoen LGTM. I added a few extra things that i noticed while testing (bugs on the lando end not your stuff). Looks like some things eg Drupal 8 search_api_solr expect custom config to exist in the core conf dir in the case where a core is specified (AFAIK a core is specified by default in newer solr versions). So something like this should "just work" now

```yaml
name: eight
recipe: drupal8
config:
  webroot: .
services:
  # Spin up a solr container called "index"
  # NOTE: "index" is arbitrary, you could just as well call this "tswift" or "covfefe"
  index:

    # Use solr version 5.5
    type: solr:6.6

    # Optionally allow access to the database at localhost:9999
    # You will need to make sure port 9999 is open on your machine
    #
    # You can also set `portforward: true` to have Lando dynamically assign
    # a port. Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app
    # portforward: 9999

    # Optionally declare the name of the solr core.
    # This setting is only applicable for versions 5.5 and above
    core: freedom

    # Optionally use custom solr config files eg (schema.xml and solrconfig.xml)
    # This is helpful if frameworks require custom config eg Drupal.
    # This is relative to the app root.
    config:
      conf: modules/contrib/search_api_solr/solr-conf/6.x
```

**Pull request merged**
