### PR TITLE
Updates CLI COLUMNS

### PR DESCRIPTION
**Pull request by gitressa**
CLI column width is set to 256 characters, which can make some lines quite long and hard to read, as well as break in non-optimal ways. For more see #1847.

> The optimal line length for your body text is considered to be 50-60 characters per line, including spaces (“Typographie”, E. Ruder). Other sources suggest that up to 75 characters is acceptable.

https://baymard.com/blog/line-length-readability

Perhaps we can set COLUMNS to 120 characters in stead, which results in about 80 characters for the description, in the right hand side?

**Now, 256 character columns**
```
$ drush help config:import
Import config from a config directory.

Arguments:
  [label] A config directory label (i.e. a key in \$config_directories array in settings.php).

Options:
  --preview[=PREVIEW] Deprecated. Format for displaying proposed changes. Recognized values: list, diff. [default: list]
  --source=SOURCE     An arbitrary directory that holds the configuration files. An alternative to label argument
  --partial           Allows for partial config imports from the source directory. Only updates and new configs will be processed with this flag (missing configs will not be deleted). No config transformation happens.
  --diff              Show preview as a diff.
```

**120 characters**
```
$ drush help config:import
Import config from a config directory.

Arguments:
  [label] A config directory label (i.e. a key in \$config_directories array in settings.php).

Options:
  --preview[=PREVIEW] Deprecated. Format for displaying proposed changes. Recognized values: list, diff. [default:
                      list]
  --source=SOURCE     An arbitrary directory that holds the configuration files. An alternative to label argument
  --partial           Allows for partial config imports from the source directory. Only updates and new configs
                      will be processed with this flag (missing configs will not be deleted). No config
                      transformation happens.
```
- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
- [ ] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by codebymikey** [comment]
I think this would make sense to be configurable (with a default value of `120`, or whatever makes the most sense).

Configuration can either be pulled in from the `~/.lando/config.yml` or from an environment variable `LANDO_COLUMNS` or `COLUMNS`.

**Comment by reynoldsalec** [comment]
@gitressa reading through the issue I think this is still a good idea (thanks for your persistence!). I was trying to make sure it doesn't interfere with and Lando ascii presentations, and I don't think it does.

Would you mind recreating this PR within https://github.com/lando/cli now that the file is over there?

**Comment by gitressa** [comment]
Sure @reynoldsalec! I have created [Reduces CLI column width from 256 to 120 characters](https://github.com/lando/cli/pull/75).

**Comment by reynoldsalec** [comment]
Awesome, I will close this PR in favor of that one, thanks @gitressa!

**Pull request closed without merging**
