### PR TITLE
Provide simpletest environment variables

### PR DESCRIPTION
**Pull request by neclimdul**
Should mostly make simpletest work out of the box.

- [ ] My code includes an update to the [CHANGELOG](https://github.com/kalabox/lando/tree/master/docs/changelog)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [ ] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by pirog** [comment]
@neclimdul this seems like a good idea to me but im wondering if we need to set this at a lower level like the php service because presumably any php driven app could be using simpletest.

@dustinleblanc is this something you could 

1. look into
2. adapt for the new rc2isms?

**Comment by neclimdul** [comment]
@pirog I'm not sure I understand the question but in this case "SIMPLETEST_" in the environment name is a Drupal legacy and drives behaviors in phpunit tests. So this is truly a "Drupal" specific thing.

**Comment by neclimdul** [comment]
From my skimming a while back, I'm not sure there is much directly salvaging this PR with how large the RC2 changes where to related code. I'll follow up in the issue.

**Comment by pirog** [comment]
@neclimdul circling back around on this, where are the `SIMPLETEST` envvars documented? 

I think we should probably adapt this and set them directly in the php service so they are available for all PHP things

**Comment by neclimdul** [comment]
Unfortunately not, they are for both 7, 8, and 9. their name is an artifact of a long dead testing framework.

I'll see if i can find some real documentation but there is some for 8 and 9 in the phpunit.xml.dist file :
https://git.drupalcode.org/project/drupal/-/blob/8.8.x/core/phpunit.xml.dist

**Comment by pirog** [comment]
Ahh nice, thanks for the context @neclimdul. I think we can probably merge this into the drupaly base recipe then

**Comment by pirog** [comment]
This has been adapted and merged into https://github.com/lando/lando/tree/rrc5a

**Comment by neclimdul** [comment]
Thanks for all the awesome work! Love all these cool changes happening

**Comment by pirog** [comment]
@neclimdul thank you! we are very much looking forward to getting that stable release out!

**Pull request closed without merging**
