### PR TITLE
Start Docker with systemctl instead of service in Linux

### PR DESCRIPTION
**Pull request by kaanklky**
Lando is trying to start docker service via service command on Linux but unfortunately major linux distributions has been switched to systemd so you need to use systemctl command instead of service command.

TODO: check if system has systemctl or service command
It will be great if check check system if it has systemctl or service command so lando can start docker service on all systemd or non-systemd distributions.

### CODE REVIEW

**Comment by dustinleblanc** [comment]
Thanks @kaanklky for the PR! It looks like the linter is failing so that needs to be tweaked real quick.

Additionally, while I agree most linux systems are probably moving to systemd, I'd be curious which distros have which init system at this point. I believe we target Fedora and Debian based systems, and I would guess both have systemd at this point.

**Comment by kaanklky** [comment]
Hello @dustinleblanc!
You can see Linux distros by init system;
For which use systemd;
[https://distrowatch.com/search.php?...](https://distrowatch.com/search.php?ostype=Linux&category=All&origin=All&basedon=All&notbasedon=None&desktop=All&architecture=All&package=All&rolling=All&isosize=All&netinstall=All&language=All&defaultinit=systemd&status=Active#simple)
For which use non-systemd;
[https://distrowatch.com/search.php?...](https://distrowatch.com/search.php?ostype=Linux&category=All&origin=All&basedon=All&notbasedon=None&desktop=All&architecture=All&package=All&rolling=All&isosize=All&netinstall=All&language=All&defaultinit=Not+systemd&status=Active#simple)

But sure it would be great if lando can check the system for init type. I tried but couldn't do that in javascript. :)

**Comment by kaanklky** [comment]
Hi @dustinleblanc,
I fixed the error but I think you must resolve conflict.

**Comment by dustinleblanc** [comment]
Thanks @kaanklky!

@pirog I think this is a good change, systemd is the init system favored by all supported distros (Debian and Fedora most of all). I'll confirm this runs on my Ubuntu box without issues, then I'd say its good to merge

**Comment by pirog** [comment]
@kaanklky @dustinleblanc definitely agree. That said would it be better to look for `systemctl` and fallback to `service` if it doesnt exit?

**Comment by dustinleblanc** [comment]
🤔 something like...
```js
var cmd = commandExists('systemctl') ? 'systemctl' : 'service';
```

Where `commandExists()` is some real function or way to find out if the command exists. It could even get masked behind something simpler like `var cmd = getInitSystemCmd()` or something...

**Comment by pirog** [comment]
Might be able to use
https://github.com/lando/lando/blob/master/lib/shell.js#L283

**Comment by dustinleblanc** [comment]
```js
var cmd = lando.shell.which('systemctl') ? 'systemctl' : 'service';
```
Sounds like it might work. @kaanklky Care to give it a try and rebase your PR on the latest upstream changes?

**Comment by kaanklky** [comment]
Thanks @dustinleblanc & @pirog!
I checked init type and returned whole command because of difference of systemctl and service commands.

Systemctl command can be used as: `systemctl {start, stop, restart, ...} service_name`
Service command can be used as: `service service_name {start, stop, restart, ...}`

**Comment by dustinleblanc** [comment]
Hey @kaanklky looks like our refactor work pulled `lib/daemon.js` out from under you :man_facepalming: 

It looks like @pirog refactored this code into `plugins/lando-engine` code.

**Comment by kaanklky** [comment]
Hey @dustinleblanc,
So what do we must do? Close PR?

**Comment by pirog** [comment]
@kaanklky i think we just need to move that code over to 
https://github.com/lando/lando/blob/master/plugins/lando-engine/lib/env.js

i'd require `shell-js` directly in that module instead of relying on `lando.shell.which` so we can keep these `lib` modules cleaner for testing.

sorry to move things around!

**Comment by dustinleblanc** [comment]
@kaanklky Let us know if you need help, I think given @pirog's last message, this can still very much be done, just as part of our newly refactored code base, thanks!

**Comment by dustinleblanc** [comment]
Hi @kaanklky! I wanted to ping you again as I am going to close this PR for now, but I want to encourage you that we still think the general idea is sound. If you can get the code in line with our post-refactor changes we'd be happy to review for inclusion in the first post 3.0 release. Thanks!

**Comment by pirog** [comment]
@dustinleblanc this is so close to done im going to reopen and just do it myself

**Comment by dustinleblanc** [comment]
@pirog Solid dude, assigned to you, moved back to in progress. Ping me when you're done and I'll review/merge

**Comment by dustinleblanc** [comment]
Updating branch to keep it fresh, @pirog should we move this to backlog?

**Comment by pirog** [comment]
Closing this in favor of https://github.com/lando/lando/pull/813

**Pull request closed without merging**
