### PR TITLE
Introduce Symfony 3.4 & 4.0 as per #307

### PR DESCRIPTION
**Pull request by legovaer**
Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**

- [x] My code passes relevant CI status checks
- [x] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [x] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [x] I have pinged @pirog/@reynoldsalec/@serundeputy when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by legovaer** [comment]
@pirog I noticed that one of the steps has failed but I can't see why. I see that something went wrong during the deployment to platform.sh. 

Could you give me some more info so that I can reproduce the issue and fix it?

**Comment by dustinleblanc** [comment]
@legovaer It looks to me like CI passed after you merged master back in, so all that's required is a review. Thanks for submitting a new Recipe! We're in the middle of some crazy refactor work at the moment before we move towards 3.0 stable, so I am not sure where we are on adding recipes, the triumvirate must convene to discuss, thanks!

**Comment by serundeputy** [comment]
@legovaer this is looking good!

* I've re-rolled for latest master
* renamed some nginx.conv files to symfonyX.conf
* addressed some code standards (mostly we are using two space indentation)
* added in `base` var to allow users to use the `via` key for apache or nginx specification

Still needs a little work to get over the finish line.  I think right now it is giving forbidden, probably because I didn't get the config right on the `symfonyX.conf` files, but I do not want to hard code the `${LANDO_WEBROOT}/web` I think that ${LANDO_WEBROOT} should pick up what the user specified with `webroot` in their `.lando.yml` file.

@legovaer if you want to address these things that would be great!  Otherwise I'll try to get back to it this weekend.

**Comment by quentint** [comment]
Hi, these recipes would be very helpful (I'm a newcomer): do you know when we'll be able to use them? Or can I use the files in https://github.com/lando/lando/tree/79cca956b5f43b5f7fd6e3022585c99c1c10dccd/plugins/lando-recipes/recipes/symfony34 and as a starting point?

Thanks for your help :)

**Pull request closed without merging**
