### PR TITLE
Update lando pantheon pull script to checkout correct branch in a pull

### PR DESCRIPTION
**Pull request by wturnerharris**
This modifies the `if` condition to check that the `$CODE` target is not in one of the protected environments since dev, test, live only track branch master. Technically, test and live track a git-tag, but that is ambiguous here.

This should prevent this from happening:

Screen Shot 2019-04-30 at 10 52 15 PM

Checklist:
- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/changelog)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [ ] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by wturnerharris** [comment]
@pirog - looks like this got marked as stale. Thoughts on this modification?

**Comment by pirog** [comment]
stale

**Comment by wturnerharris** [comment]
@pirog - love the work your team has been doing, and excited for the sunset of Kalabox, dawn of Lando. I'm writing a lot of CI-related bash scripts for our agency, so let me know if I can help in any way.

**Comment by pirog** [comment]
nice! thanks @wturnerharris. 

we are going to be doing some lando outreach throughout the rest of the year to try and build out a sustainable community to drive lando for the long term. a HUGE part of that will be engaging better with our contributors (like you!) so stay tuned for that.

in the meantime, unstaleing this again :/

**Comment by pirog** [comment]
@wturnerharris finally on this! looks like a solid change

**Pull request merged**
