### PR TITLE
GUIDE: Adding run lando funcitonal tests locally guide.

### PR DESCRIPTION
**Pull request by serundeputy**
@pirog I added a `Contributor` category for this guide ... if you don't like that let me know and I can remove ... in that case let me know how you'd like to categorize it.

### CODE REVIEW

**Comment by pirog** [comment]
@serundeputy i think it might make more sense to add these directly to our contributing code docs as opposed to a guide
https://docs.lando.dev/contrib/contrib-testing.html#functional-tests

what do you think?

**Comment by serundeputy** [comment]
@pirog I'll spin it out to the docs proper.

**Comment by serundeputy** [comment]
@pirog updated to move to docs proper.

**Comment by pirog** [comment]
@serundeputy merged

**Pull request merged**
