### PR TITLE
phpMyAdmin themes

### PR DESCRIPTION
**Pull request by thejacer87**

### CODE REVIEW

**Comment by pirog** [comment]
@thejacer87 im going to adapt this into the new Lando guide format but will still give you credit for it! Do you have any problem being listed on the Lando site as a contributor?

**Comment by thejacer87** [comment]
sounds good to me!

but fyi, since the move to phpmyadmin 5 by default, phpmyadmin no longer supported by them

https://www.phpmyadmin.net/themes/
> Themes are provided by third parties and the phpMyAdmin team does not provide any support for them, please contact original authors for improvements or security fixes.

**Comment by pirog** [comment]
@thejacer87 my read on that is you can still use them they just arent something the phpmyadmin team is going to support but ill let you know in a bit!

**Comment by pirog** [comment]
@thejacer87 alright, this is in the consolidation branch over here https://github.com/lando/lando/pull/2124
closing this in favor of that

**Pull request closed without merging**
