### PR TITLE
Followup to #1390: old syntax for overrides has services key

### PR DESCRIPTION
**Pull request by benjifisher**
Thank you so much for contributing code to Lando! If this is your **first time** contributing to Lando we recommend you check out

* [Contributing to Lando](https://docs.devwithlando.io/contrib/contributing.html)
* [Lando Developer Guide](https://docs.devwithlando.io/dev/started.html)

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/changelog)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [x] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by benjifisher** [comment]
Since #1390 is already closed and there is no issue for this follow-up, I did not use the standard format for branch name and commit message. I suppose you can fix up the latter when you merge.

**Comment by pirog** [comment]
@benjifisher totally reasonable on the format difference. Thanks for the PR. It saves us a lot of time to get PRs to fix the docs instead of getting an issue asking us to make a few small edits!

**Comment by benjifisher** [comment]
I assume the CI failure was random. I did notice that I used hard tabs in the markdown file ...

**Comment by pirog** [comment]
seems like travis has been a bit fickle today so i dont think it was a critical failure. We use spaces instead of tabs but shouldnt really matter for docs.

**Pull request merged**
