### PR TITLE
Add support for proxying from subdirectories

### PR DESCRIPTION
**Pull request by bartlangelaan**
<details>
 <summary>Default issue template</summary>
Thank you so much for contributing code to Lando! If this is your **first time** contributing to Lando we recommend you check out

* [Contributing to Lando](https://docs.devwithlando.io/contrib/contributing.html)
* [Lando Developer Guide](https://docs.devwithlando.io/dev/started.html)

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [X] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/help)
- [X] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [ ] My code includes documentation updates if applicable.
- [x] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.
</details>

This pull request adds support for serving apps from a subdirectory.

When a subdirectory is added to the proxy array, it will add the right traefik rule which will then serve the subdirectory from that path as if it was the root path.

Please see the functional test for an example.

### CODE REVIEW

**Comment by bartlangelaan** [comment]
Not stale

**Comment by bartlangelaan** [comment]
Not stale I think..?

**Comment by bartlangelaan** [comment]
So I guess I'll just keep commenting :-)

**Comment by bartlangelaan** [comment]
So I guess I'll just keep commenting :-)

**Comment by pirog** [comment]
@bartlangelaan very smooth feature! sorry for the delay getting to it!

**Comment by pirog** [comment]
@bartlangelaan  great work on this. merged into a consolidation branch over here https://github.com/lando/lando/pull/2124. should be able to drop it in the next release

**Pull request closed without merging**
