### PR TITLE
Change $PATH directory order for the pantheon recipe

### PR DESCRIPTION
**Pull request by uberhacker**
- [x] My code includes the latest code from the `master` branch
- [x] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/help)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [x] My code includes documentation updates if applicable.
- [x] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by kdoylesei** [comment]
This would be a big help for me so I can match my local env with Pantheon.

**Comment by uberhacker** [comment]
Need to fix merge conflict.

**Comment by uberhacker** [comment]
@pirog: Do you think this is worth merging or should I just close?

**Comment by uberhacker** [comment]
Unstale.

**Comment by pirog** [comment]
@uberhacker since this is such a low level change im guessing this may produce undesirable results elsewhere. My guess is once we update the Pantheon recipe to have more native handling of newer versions of Drush this will no longer be required.

**Pull request closed without merging**
