### PR TITLE
remind after init that lando pull is likely next step

### PR DESCRIPTION
**Pull request by ownsourcing**
easy to forget if you go away from Lando for a little while, and to sit staring at a flashing terminal prompt and a 500 error in your browser

Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**

- [x] My code passes relevant CI status checks
- [x] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [ ] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [ ] I have pinged @pirog/@reynoldsalec/@serundeputy when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by ownsourcing** [comment]
most of the checkboxes don't really apply to this small (but ideally useful) cli ui change

**Comment by pirog** [comment]
@ownsourcing definitely not opposed to this change in spirit but only one of our 10+ recipes has a `lando pull` command so we probably want to isolate this UX change to only show up on recipes where that command exists

**Comment by ownsourcing** [comment]
@pirog agreed; at current familiarity with this codebase, just not sure how to pull off that distinction. Happy to submit a new pull request if you can give a pointer or two?

**Comment by dustinleblanc** [comment]
@ownsourcing You'd want to look exclusively inside the Pantheon recipe within `plugins/lando-recipes/recipes/pantheon`.

**Comment by dustinleblanc** [comment]
Also, might be +1 to prompt the user with a y/n if they want to pull

**Comment by dustinleblanc** [comment]
Hi @ownsourcing! I am closing this PR for now since we haven't had any activity for a while and we're prepping for a new release soon. We're in bug-fix / refactor mode at the moment. If you'd like to reopen this or submit a new PR against the Pantheon recipe exactly, we'd be glad to review after we complete the 3.0 release cycle, thanks!

**Pull request closed without merging**
