### PR TITLE
Update solr.md with jump-start instructions

### PR DESCRIPTION
**Pull request by froboy**
This updates the solr docs with updated paths (`sites/all/modules` isn't where most folks store their code anymore) and also points to the [jump-start](https://www.drupal.org/project/search_api_solr/issues/3070455) config now available in search_api_solr 4.x.

Thanks for your consideration!

----------

Thank you so much for contributing code to Lando! If this is your **first time** contributing to Lando we recommend you first check our [Getting Involved](https://docs.lando.dev/contrib/contributing.html) docs.

It may also be useful to check the below documentation based on what you are trying to do:

* [Adding code to Lando](https://docs.lando.dev/contrib/contrib-intro.html)
* [Updating documentation](https://docs.lando.dev/contrib/contrib-intro.html)
* [Working on DevOps](https://docs.lando.dev/contrib/contrib-intro.html)
* [Working on Lando's auxiliary services eg websites, apis, etc](https://docs.lando.dev/contrib/contrib-intro.html)
* [Writing Lando Guides](https://docs.lando.dev/contrib/guides-intro.html)
* [Writing Lando blog posts](https://docs.lando.dev/contrib/blogging-intro.html)

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
- [ ] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [x] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by froboy** [comment]
To test:
- Add a solr service to your `.lando.yml`:

```
  solr:
    type: solr:8
    portforward: true
    core: my_core
    config:
      dir: web/modules/contrib/search_api_solr/jump-start/solr8/config-set
 ```
- `lando rebuild -s solr`
- `lando ssh -s solr` then `ls -la /var/solr/data/search_api_solr_8.x-3.0/conf/`
- observe those files match the ones in the config directory.
- observe the solr core starts successfully and doesn't have any errors in the ui

**Comment by reynoldsalec** [comment]
Hey @froboy thanks for the contribution!

We've moved the docs to their own repo: https://github.com/lando/docs

Would you mind moving this PR over there? Thanks again for the help!

**Comment by reynoldsalec** [comment]
Moved this over to https://github.com/lando/docs/pull/163, thanks @froboy, hopefully got the attribution right!

**Comment by froboy** [comment]
@reynoldsalec sorry for the delay here. Thanks for moving it over and the attribution!

**Pull request closed without merging**
