### PR TITLE
Spell check and grammar changes to docs/contrib/*.md

### PR DESCRIPTION
**Pull request by uberhacker**
- [x] My code includes the latest code from the `master` branch
- [x] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
- [ ] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [x] My code includes documentation updates if applicable.
- [x] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by smutlord** [comment]
@uberhacker this looks good and we very much appreciate spelling and grammar improvements. Definitely keep those coming!

To help move things along faster in the future we recommend:

1. PR changes in smaller chunks. 
2. Try to keep it grammar and spelling focused (as the title of this PR implies), there is a fair amount of editorial in these changes which we are probably not going to accept. even if we do end up accepting them it adds significant overhead to the PR since editorial changes are things that generally require much more internal discussion than easier grammar/spell changes. If you have proposed editorial changes id suggest putting those in a separate PR for a cleaner separation of concerns.

Thanks again.

**Comment by uberhacker** [comment]
Hey @smutlord:
I appreciate the feedback.  Sorry, I'm not sure what you mean by editorial changes.  What specifically are you referring to?  Personally, I think separating the concerns makes it more difficult to merge all the PRs together since it creates greater potential for merge conflicts with other PRs.  I've already resolved merge conflicts 4 times since this has been sitting in the queue so long.

**Comment by smutlord** [comment]
@uberhacker removing words and changing the meaning of content would be considered editorial. 

as one of the people who is personally responsible for merging things im telling you what would both be easier for me and as a consequence what would cause this to not sit around in the queue for so long. if anything, the chance for merge conflicts would be greater on a larger and more monolithic PR like this one.

if you dont want to do any of that thats fine by me, it just will increase the time to merge

**Comment by smutlord** [comment]
This has been consolidated over here
https://github.com/lando/lando/pull/2245

**Comment by uberhacker** [comment]
Sorry, I'm still not understanding specifically what you consider changing the meaning.  I don't see that anywhere.

**Pull request closed without merging**
