### PR TITLE
Firstpost

### PR DESCRIPTION
**Pull request by purdy**
Thank you so much for contributing code to Lando! If this is your **first time** contributing to Lando we recommend you first check our [Getting Involved](https://docs.lando.dev/contrib/contributing.html) docs.

It may also be useful to check the below documentation based on what you are trying to do:

* [Adding code to Lando](https://docs.lando.dev/contrib/contrib-intro.html)
* [Updating documentation](https://docs.lando.dev/contrib/contrib-intro.html)
* [Working on DevOps](https://docs.lando.dev/contrib/contrib-intro.html)
* [Working on Lando's auxiliary services eg websites, apis, etc](https://docs.lando.dev/contrib/contrib-intro.html)
* [Writing Lando Guides](https://docs.lando.dev/contrib/guides-intro.html)
* [Writing Lando blog posts](https://docs.lando.dev/contrib/blogging-intro.html)

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [X] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
- [ ] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [ ] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [X] My code includes documentation updates if applicable.
- [ ] My code passes relevant CI status checks
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by pirog** [comment]
@purdy this is great but may be better as a GUIDE than a BLOG POST. Check this out and let me know if you agree!
https://docs.lando.dev/contrib/guides-intro.html#what-is-a-guide

**Comment by purdy** [comment]
Oh, cool ... I agree ... I'll redo and resubmit. Thanks!

**Comment by pirog** [comment]
nice @purdy this is looking good. here are a few other things id consider doing to take things to the next level

1. Make the guide _just_ about pulling a database backup from pantheon, pulling a backup from a generic location would be an awesome SEPARATE guide, 
2. Make the title more specific eg something like "Updating your Pantheon site from the latest DB backup" that way people can easily find this with the obvious google key words
3. Create a new guide "category" for pantheon https://docs.lando.dev/contrib/guides-advanced.html#adding-a-category and drop this guide in there instead
4. Use markdown codeblocks to format the code things https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Let me know if you need an assist with help with any of them, im happy to help!

**Comment by purdy** [comment]
Thanks, @pirog! I just committed an update that should address these points.

**Comment by pirog** [comment]
alright alright alright! i think this is ready for primetime!

**Comment by pirog** [comment]
thanks @purdy!

**Pull request merged**
