### PR TITLE
adds troubleshooting for Linux

### PR DESCRIPTION
**Pull request by alexfornuto**
Documents some issues that through me for a loop while installing Lando from source.

- [x] My code passes relevant CI status checks
- [x] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [ ] I have pinged @pirog when I think my code is ready for prime time.

### CODE REVIEW

**Comment by alexfornuto** [comment]
@pirog Does this count as a ping?

**Comment by pirog** [comment]
@alexfornuto this looks great. only suggestion is instead of having a troubleshooting section under the "install from source" section, you bump it up to the linux section as some sort of "caveats" subsection.

what do you think?

**Comment by alexfornuto** [comment]
@pirog I've move it as suggested, but I'm not sure if The header is still at the right level. This document uses two different forms of Header markdown (underlines `---` `===` and octothorpes `###`) which makes it hard to determine nesting level.

**Comment by pirog** [comment]
As far as i know 

```
= -> h1
- -> h2
### -> h3
#### - > h4
```

so im guessing you want `###`?

**Comment by alexfornuto** [comment]
@pirog You could standardize it as:

```
# => H1
## => H2
### => H3
#### => H4
```

But that may just be a personal preference.

**Comment by pirog** [comment]
Yeah, i know that is a common way to do it. 

Personally i find using `==` and `--` for the `h1` and `h2` to be a bit more readable when you are looking at lots of markdown files all the time... as a sadly am :(

**Pull request merged**
