### PR TITLE
Add support for SOLR 8

### PR DESCRIPTION
**Pull request by hussainweb**
Thank you so much for contributing code to Lando! If this is your **first time** contributing to Lando we recommend you check out

* [Contributing to Lando](https://docs.devwithlando.io/contrib/contributing.html)
* [Lando Developer Guide](https://docs.devwithlando.io/dev/started.html)

We will get to your PR as soon as we can but in the meantime you might want to check to make sure you have done the following. **The more boxes you can check the easier it will be for us to merge in your changes with confidence**

- [x] My code includes the latest code from the `master` branch
- [x] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/help)
- [ ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [ ] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [x] My code includes documentation updates if applicable.
- [x] My code passes relevant CI status checks
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by hussainweb** [comment]
I am not sure why platfomsh task is failing as I cannot open the link for some reason.

**Comment by hussainweb** [comment]
@pirog @dustinleblanc may I please ask you for this review? Thanks!

**Comment by pirog** [comment]
yes, test, definitely

**Comment by michaelstrelan-catalyst** [comment]
Could be an issue that start-solr.sh is still trying to copy the config to `/opt/solr/server/solr/mycores/` instead of `/var/solr/data`.

This is the workaround that worked for me:

```
services:
  solr:
    type: solr
    portforward: true
    core: my-custom-core
    config:
      dir: config/solr/8.x
    overrides:
      image: solr:8.2.0
    build_as_root:
      - mkdir -p /opt/solr/server/solr/mycores/my-custom-core/conf
      - chown -R solr /var/solr
      - chown -R solr /opt/solr/server/solr/mycores
```

**Comment by tormi** [comment]
not stale

**Comment by milkovsky** [comment]
Could you please re-open the issue?

**Comment by pirog** [comment]
@smutlord has merged this into #2090

**Comment by vlyalko1972** [comment]
I am trying to switch solr to 8.5 or 8.6 and getting error that it is not supported. Will lates versions of solr be supported any time soon? Thank you!

**Pull request closed without merging**
