### PR TITLE
Update `lamp` recipe to merge pre-configured services

### PR DESCRIPTION
**Pull request by RobinHoutevelts**
Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**

- [x] My code passes relevant CI status checks
- [ ] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [x] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [ ] My code includes documentation updates if relevant.
- [ ] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by RobinHoutevelts** [comment]
This PR fixes #853, #843, #671, #593 and probably a few other concerning overriding database credentials.

The main issue is that while the `lamp` recipe is responsible for creating the `DB_*` ENV variables on the `appserver`, it has no way of knowing if the user altered the `database` service in the `.lando.yml` file.

While the `mysql` service, _does_ pick up this change and creates the expected user and database.

This caused a lot of confusion.

**Comment by RobinHoutevelts** [comment]
Basically it's now possible for a recipe to see if a user's `.lando.yml` already defined services. Before it could only see config.

And with that new possibility the `lamp` recipe can insert overridden `database.cred` into the ENV, fixing those issues.

@pirog If for some reason this is a no-no, you can close the PR as my understanding of lando is a bit better now and I have alternatives lined up.

**Comment by pirog** [comment]
This is great and reading through the issue you posted actually makes me
more convinced this is a bug.

That all said, I think we got an opportunity here to resolve or move along
other impacted and/or related issues in one swift stroke by expanding the
scope of this a bit. I also think we want to change the implementation here
to work within the recipe->services control flow a bit better.

I’m AFK right now but I’ll try to pull in related issues with a set of
action items on your ticket when I’m back so we can move this great
improvement along

**Comment by RobinHoutevelts** [comment]
@pirog Ok to close this PR since we've opted to go for more robust changes?

( Having `db-*` commands target the `database` service and deprecating `DB_*` env vars. https://github.com/lando/lando/issues/853#issuecomment-377873589)

**Comment by pirog** [comment]
@RobinHoutevelts yes, good call!

**Pull request closed without merging**
