### PR TITLE
Clarify Lando docs

### PR DESCRIPTION
**Pull request by anavarre**
This should help people not fall into the trap of #520.

### CODE REVIEW

**Comment by pirog** [comment]
@anavarre i think having this clarification is good but we might want to clarify the clarification. Lando WILL install a codebase for you if you use either the `pantheon` or `github` initialization methods. But a straight up `lando init` is intended for usage in an already existing codebase, i think this is the case we want to clarify. 

Let me know if you can make those changes and then i'll merge! Thanks for your help!

**Comment by anavarre** [comment]
@pirog sure, I've clarified this. Does it make more sense as is?

**Comment by pirog** [comment]
@anavarre yes! thanks so much for helping.

**Comment by ujeshurun** [comment]
Sorry, I am a newcomer to this, so forgive me if I ask any silly questions. But just to get this understood, if I wanted to have lando spin up a new wordpress instance, I CANNOT SIMPLY RUN `lando init`?

**Comment by serundeputy** [comment]
@ujeshurun that is correct.

You need to either download a new wordpress code base or a wordpress site you already have; `cd into the wordpress directory` then `lando init`

**Pull request merged**
