### PR TITLE
Add instructions on how to convince others to sponsor Lando.

### PR DESCRIPTION
**Pull request by reynoldsalec**
Updating the docs to fix some dead links; refactored their old target page to focus on convincing other people/orgs to sponsor Lando.

- [x] My code includes the latest code from the `master` branch
- [ ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/help)
- [x] My code includes a [functional test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [x] My code includes a [unit test](https://docs.lando.dev/contrib/contrib-testing.html) if applicable
- [x] My code includes documentation updates if applicable.
- [x] My code passes relevant CI status checks
- [x] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Nice, I just asked my company for a "monthly engineer sponsorship stipend", e.g. $100/month to sponsor projects we like and use for work!

**Comment by ElijahLynn** [comment]
Also, it might be easier for companies to one-off send in some cash. The monthly recurring might not be doable for some. e.g. I could pull off a single $50 on my card right now, but monthly would get more scrutiny.

**Comment by ElijahLynn** [comment]
I see now, that OpenCollective allows for one-time donations. Might be good to highlight that option with instructions for that audience > https://opencollective.com/lando

**Review by serundeputy — APPROVED** [review]

**Comment by serundeputy** [comment]
@reynoldsalec I approve of this messaging.

might be worth a look at @ElijahLynn 's suggestions, but we can either merge now and incorporate after or if it is simple incorporate suggestions now and then merge ... i'm fine with either.

**Comment by ElijahLynn** [comment]
> might be worth a look at @ElijahLynn 's suggestions, but we can either merge now and incorporate after or if it is simple incorporate suggestions now and then merge ... i'm fine with either.

I just broke that out into a new issue. Seems like it would be best to merge this as-is, as it is an improvement.

**Pull request merged**
