### PR TITLE
Fix config entry preventing to launch php53 appserver

### LINKED ISSUE #652: php 5.3 service via apache cannot inject config
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

Lando-master - macOS High Sierra 10.13.2 (17C205) 

**Tell us about your `.lando.yml`**

```
# LAMP stack example
name: NAME

# Give me http://lamp.lndo.site and https://lamp.lndo.site
proxy:
  appserver:
    - NAME.lndo.site

# Spin up services to run a basic LAMP stack
services:

  # Create a php 5.3 instance served by the latest apache with https turned on
  appserver:

    # PHP version 5.3
    type: php:5.3

    # Serve php by either apache or nginx. You can put in any `service:version`
    # string that is supported by Lando's nginx and apache services.
    via: apache

# Add some nice command routing
tooling:
  php:
    service: appserver
```

I am getting the following error with several apps, but this one is very simple, just static PHP:

```
$ lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.3-alpine)...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "serberlawfirm_default" with the default driver
Creating volume "serberlawfirm_appserver" with default driver
Creating volume "serberlawfirm_data" with default driver
Pulling appserver (devwithlando/php:5.3-apache)...
Creating serberlawfirm_appserver_1 ... error

ERROR: for serberlawfirm_appserver_1  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/ariel/.lando/services/config/php/php.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged\\\" at \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged/usr/local/etc/php/conf.d\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for appserver  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/ariel/.lando/services/config/php/php.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged\\\" at \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged/usr/local/etc/php/conf.d\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
error:  Error: Error
    at /Users/ariel/Work/lando/lib/promise.js:56:17
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at rec (/Users/ariel/Work/lando/lib/promise.js:42:13)
    at /Users/ariel/Work/lando/lib/promise.js:50:20
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at /Users/ariel/Work/lando/lib/promise.js:49:12
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I am also on latest docker edge and tried resetting docker to default and pulling everything again.

I am not sure if this is lando, but any ideas?

### PR DESCRIPTION
**Pull request by hanoii**
Fixes #652

### CODE REVIEW

**Comment by serundeputy** [comment]
Thanks @hanoii !
@pirog Works as advertised!
RTBC

**Comment by pirog** [comment]
@hanoii @serundeputy closing this but i merged it into our refactor branch to it will get to master that way!

**Comment by hclsorna** [comment]
Hi Guys,

How soon can we expect this fix to move to master?

**Comment by pirog** [comment]
@hclsorna as far as i know it is in master
https://github.com/lando/lando/blob/master/plugins/lando-services/services/php/php.js#L96

probably wont be in an official release for awhile since master is a bit in flux right now

**Pull request closed without merging**
