### PR TITLE
Add Installation instructions for homebrew users

### PR DESCRIPTION
**Pull request by wturnerharris**
Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**

- [ ] My code passes relevant CI status checks
- [ ] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [ ] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [x] My code includes documentation updates if relevant.
- [ ] I have pinged @pirog/@reynoldsalec/@serundeputy when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by dustinleblanc** [comment]
Hey @wturnerharris! Who is maintaining the brew cask? Will this get updated automatically when we cut new releases? If not, I think it'd be good to add a disclaimer that the builds can be out of date (as many other projects do).

Install via Brew is dope though!

**Comment by wturnerharris** [comment]
@dustinleblanc - [Looks](https://github.com/commitay/homebrew-cask/commits/master/Casks/lando.rb) to be community-maintained like most homebrew packages, so a disclaimer is probably warranted. I'm sure this can be automated on the lando side following releases, updating the sha hash, version string, and checkpoint hash.

**Comment by wturnerharris** [comment]
@dustinleblanc - I added the disclaimer. Let me know if there's anything else to update for docs-only PR.

**Comment by dustinleblanc** [comment]
On a side note, it kind of looks automatable... @pirog, worth an issue to have that looked at sometime?

**Comment by dustinleblanc** [comment]
Appveyor is blocking me from merging this, but I think this is ready to go

**Comment by pirog** [comment]
@dustinleblanc i scaled back the status check requirements for PRs which was causing that blocking appveyor build.

**Pull request merged**
