### PR TITLE
Update drupal8.md

### PR DESCRIPTION
**Pull request by AmyJuneH**
git clone -b 8.x https://github.com/drupal/drupal.git mysite

should be 

git clone -b 8.5.x https://github.com/drupal/drupal.git mysite

Thank you so much for contributing code to lando!

We will get to your PR as soon as we can but in the meantime you might want to
check to make sure you have done the following. **The more boxes you can check
the easier it will be for us to merge in your changes with confidence**

- [ ] My code passes relevant CI status checks
- [ ] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [ ] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [ ] My code includes documentation updates if relevant.
- [ ] I have pinged @pirog/@reynoldsalec/@serundeputy when I think my code is ready for prime time.

If you are unclear about any of the above please add comments below so we can
improve our process.

### CODE REVIEW

**Comment by pirog** [comment]
@AmyJuneH @sk33lz oh interesting. i didn't know D8 was branching this way for minor versions, makes sense i guess. 

Sort of annoying that we will be forced to update this as we go... maybe there is a more robust solution EG instead of git cloning maybe we can curl/wget some sort of "latest" D8 package. 

I'll merge this in for now but if either of you have energy to change the docs to address the brittleness of this it would be much appreciated!

**Comment by pirog** [comment]
Enjoy the beautiful American Paradise that is Worcester, MA!

**Comment by jeffymahoney** [comment]
Nice :)
Here's what we can change the docs to (sorry, no time today to get the repo and create a proper PR right now.)

```
# See: https://github.com/drupal/drupal
git clone https://github.com/drupal/drupal.git mysite
```

Just leave off the -b option and after the clone, you'll be on 8.5.x. Also note that the link in the comment needs to be updated. The old link, https://github.com/drupal/drupal/tree/8.x , is outdated.

Peash :)

**Comment by jeffymahoney** [comment]
And thanks for making this change. It really helps out people who are still learning the ropes.

**Pull request merged**
