### PR TITLE
Issue #1987: Set PATH_INFO and PATH_TRANSLATED for Pantheon Nginx containers

### PR DESCRIPTION
**Pull request by dustinleblanc**
This is done on Pantheon and seems to be needed for the latest versions
of SimpleSaml. Researching these params for NGINX in general, it seems
these values are actually set by default:

@see https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

I've tried to write some func tests for this based on the example above, but I can't get it to work. @pirog I am not sure if the place I editted this is getting loaded correctly.

### CODE REVIEW

**Comment by pirog** [comment]
@dustinleblanc you got anything i can look at re: tests? Might help me figure out what exactly you are trying to do!

**Comment by dustinleblanc** [comment]
@pirog just put in a WIP test to try to replicate what's listed in the nginx docs

**Comment by pirog** [comment]
Nice thanks @dustinleblanc. So my feedback would be 

* Is it safe to set `PATH_INFO` at such a low level as the `nginx` service? Is this something that is going to behave across ANYTHING we implement using that service? Looks like our Drupal 8 recipe sets it but our WordPress recipe does not. Maybe it's good to set at such a low level but the issue is definitely scoped for _just_ Pantheon i think. 
* It does look like our default nginx pantehon configs have a comment for presumably this exact thing
https://github.com/lando/lando/blob/master/plugins/lando-pantheon/recipes/pantheon/drupal8.conf.tpl#L154 however it also seems like this comment is quickly revealed to be a lie. These configs are adapted directly from Pantheon so you could `sftp` to a pantheon instance and find the updated nginx config
* For the test it might be simpler and more reliable to use `php -i` and just grep for what you need

Hope that helps!

**Comment by dustinleblanc** [comment]
Thanks @pirog! pulling Pantheon config files via SFTP is actually how I landed on this fix. Pantheon has a fastcgi_params file that is nearly identical to ours but includes a couple of Pantheon specific things at the end.

The concern about the global changes to nginx are ones I share. What I think might be better here is creating a new fastcgi_params file in the pantheon recipe, just wasn't sure how to make sure that is loaded correctly. I'll give the php -i route a try and see if I can scope the fastcgi_params

**Comment by dustinleblanc** [comment]
Alright, scoped how we include the prepend.php with a volume and just copied that the for the fastcgi_params file, and then just updated the include path, which is what Pantheon was doing too. Testing it out

**Comment by pirog** [comment]
@dustinleblanc also looking at this more im wondering why we excluded `PATH_INFO` and `PATH_TRANSLATED` from our default nginx `fastcgi_params` file to begin with. Let me git history that file and see if it reveals anything

**Comment by dustinleblanc** [comment]
Okay got the tests passing for this and scoped it to Pantheon in general. I mimic'd their `srv/includes/fastcgi_params` setup on the platform. I can confirm PATH_INFO gets set in the $_SERVER array, but it seems to be empty for the requests I've tested.

Also had to do a slight refactor of the constructor to make code climate happy, that could probably be carried a little further with those functions pulled into the utils in the lib folder.

**Comment by pirog** [comment]
nice @dustinleblanc! super helpful and much appreciated. 

i think we can def just :shipit: this as is. that said and having done some more research i also feel like we might want to revisit our default `nginx` config to include these params as well aka this is the opposite of my original thinking. what do you think? if we feel like that is a good idea i can probably adapt your work here for teh more general case and we can leave pantheon as a special case.

**Comment by dustinleblanc** [comment]
Yeah given that the documentation for nginx _seems_ to indicate that this is just casual normal settings, it feels safe to set everywhere, but I do have that slightly nagging feeling that you were right and something in a far off land, hidden from our view may quietly break 🙈

**Comment by pirog** [comment]
@dustinleblanc ended up just setting the nginx defaults, but merged your other changes in as well. all over in #2123 now! going to close this...

also, no matter what i do i cant seem to get `PATH_INFO` to have a value of any kind... that doesnt seem right to me?

**Comment by dustinleblanc** [comment]
In regards to getting `PATH_INFO` to have actually things, the test scenario from nginx suggests you need something like:

```
// test.php
<?php var_export($_SERVER); ?>

request to -> http://server/test.php/foo/bar.php
```
Then path info should say something like `foo/bar.php` or something.

With our nginx rules that smartly rewrite these requests, I think it just isn't possible to make it show up properly. For most Drupaly recipes I think it just takes that request and routes it to index.php for Drupal to handle.

**Comment by pirog** [comment]
@dustinleblanc i tried doing something similar to that in the `php` example but still got nothing, ditto for drupals `/admin/status/report/php` phpinfo() path. 🤷‍♂ for sure but at least it exists now and we can take it from there

**Pull request closed without merging**
